import { SupportedLanguageCode } from '@/context/LanguageContext';

export interface VernacularGuidelines {
  title: string;
  subtitle: string;
  emergencyContactsTitle: string;
  contacts: { name: string; number: string; description: string }[];
  categories: {
    disaster: string;
    typeKey: string;
    severity: string;
    beforeTitle: string;
    before: string[];
    duringTitle: string;
    during: string[];
    afterTitle: string;
    after: string[];
    officialResourcesTitle: string;
    resources: { name: string; url: string }[];
  }[];
  additionalResourcesTitle: string;
  additionalResources: { name: string; url: string }[];
}

export const VERNACULAR_GUIDELINES: Record<SupportedLanguageCode, VernacularGuidelines> = {
  ml: {
    title: 'ദുരന്ത നിവാരണ സുരക്ഷാ മാർഗ്ഗരേഖകൾ',
    subtitle: 'കേന്ദ്ര-സംസ്ഥാന ദുരന്ത നിവാരണ അതോറിറ്റികളുടെ ഔദ്യോഗിക നിർദ്ദേശങ്ങൾ',
    emergencyContactsTitle: 'അടിയന്തര സഹായ നമ്പറുകൾ',
    contacts: [
      { name: 'എൻ.ഡി.ആർ.എഫ് ഹെൽപ്പ്‌ലൈൻ', number: '011-24363260', description: 'ദേശീയ ദുരന്ത നിവാരണ സേന' },
      { name: 'പോലീസ് കൺട്രോൾ റൂം', number: '100 / 112', description: 'അടിയന്തര പോലീസ് സഹായം' },
      { name: 'ഫയർ & റെസ്ക്യൂ സർവീസ്', number: '101', description: 'തീപിടുത്തം, രക്ഷാപ്രവർത്തനം' },
      { name: 'ആംബുലൻസ് സർവീസ്', number: '102 / 108', description: 'അടിയന്തര മെഡിക്കൽ സർവീസ്' },
      { name: 'സംസ്ഥാന ദുരന്ത നിവാരണം', number: '1070 / 1077', description: 'കലക്ടറേറ്റ് എമർജൻസി ഓപ്പറേഷൻസ്' },
      { name: 'വനിതാ ഹെൽപ്പ്‌ലൈൻ', number: '1091', description: 'സ്ത്രീ സുരക്ഷാ സഹായം' },
    ],
    categories: [
      {
        disaster: 'പ്രളയ സുരക്ഷ',
        typeKey: 'flood',
        severity: 'അതിതീവ്രം',
        beforeTitle: 'വെള്ളപ്പൊക്കത്തിന് മുൻപ്:',
        before: [
          'പ്രദേശത്തെ പ്രളയ സാധ്യതകളും ഉയർന്ന രക്ഷാകേന്ദ്രങ്ങളും മനസ്സിലാക്കുക',
          'പ്രധാന രേഖകളും തിരിച്ചറിയൽ കാർഡുകളും വാട്ടർപ്രൂഫ് ബാഗുകളിൽ സൂക്ഷിക്കുക',
          'കുടിവെള്ളം, ഉണങ്ങിയ ഭക്ഷണങ്ങൾ, പ്രഥമശുശ്രൂഷാ കിറ്റ് എന്നിവ ഉയർന്ന നിലയിൽ കരുതുക',
          'വൈദ്യുതി, ഗ്യാസ് കണക്ഷനുകൾ ആവശ്യമെങ്കിൽ ഓഫ് ചെയ്യാൻ പരിശീലിക്കുക',
        ],
        duringTitle: 'വെള്ളപ്പൊക്ക സമയത്ത്:',
        during: [
          'ഉടൻ തന്നെ സുരക്ഷിതമായ ഉയർന്ന പ്രദേശങ്ങളിലേക്കോ ക്യാമ്പുകളിലേക്കോ മാറുക',
          'ഒഴുക്കുള്ള വെള്ളത്തിലൂടെ നടക്കുകയോ വാഹനം ഓടിക്കുകയോ ചെയ്യരുത്',
          'വൈദ്യുത ലൈനുകൾ, ട്രാൻസ്ഫോർമറുകൾ എന്നിവയിൽ നിന്ന് അകന്നുനിൽക്കുക',
          'ഔദ്യോഗിക അറിയിപ്പുകളും മുന്നറിയിപ്പുകളും നിരന്തരം ശ്രദ്ധിക്കുക',
        ],
        afterTitle: 'വെള്ളപ്പൊക്കത്തിന് ശേഷം:',
        after: [
          'അധികൃതരുടെ സുരക്ഷാ നിർദ്ദേശം ലഭിച്ച ശേഷം മാത്രം വീട്ടിലേക്ക് മടങ്ങുക',
          'മലിനമായ വെള്ളം കുടിക്കരുത്; തിളപ്പിച്ചാറിയ വെള്ളം മാത്രം ഉപയോഗിക്കുക',
          'വീട്ടിലെ ഇലക്ട്രിക്കൽ ഉപകരണങ്ങൾ ഉണങ്ങിയ ശേഷം മാത്രം പ്രവർത്തിപ്പിക്കുക',
          'നാശനഷ്ടങ്ങളുടെ ചിത്രങ്ങൾ എടുത്ത് സൂക്ഷിക്കുക',
        ],
        officialResourcesTitle: 'ഔദ്യോഗിക വിവരങ്ങൾ:',
        resources: [
          { name: 'ദേശീയ ദുരന്ത നിവാരണ അതോറിറ്റി (NDMA)', url: 'https://ndma.gov.in/' },
          { name: 'കേരള സംസ്ഥാന ദുരന്ത നിവാരണ അതോറിറ്റി (KSDMA)', url: 'https://sdma.kerala.gov.in/' },
        ],
      },
      {
        disaster: 'ഭൂകമ്പ സുരക്ഷ',
        typeKey: 'earthquake',
        severity: 'തീവ്രം',
        beforeTitle: 'ഭൂകമ്പത്തിന് മുൻപ്:',
        before: [
          'ഭാരമുള്ള അലമാരകളും ഉപകരണങ്ങളും ഭിത്തിയിൽ ഉറപ്പിച്ചു നിർത്തുക',
          'ഓരോ മുറിയിലും ഉറപ്പുള്ള മേശകൾക്ക് താഴെ സുരക്ഷിത സ്ഥാനം കണ്ടെത്തുക',
          'അടിയന്തര കിറ്റും ടോർച്ചും സദാ സജ്ജമാക്കി വെക്കുക',
          'കെട്ടിടത്തിന് പുറത്തുകടക്കാനുള്ള വഴികൾ തടസ്സമില്ലാതെ സൂക്ഷിക്കുക',
        ],
        duringTitle: 'ഭൂകമ്പ സമയത്ത്:',
        during: [
          'താഴെ ഇരിക്കുക, തല മറയ്ക്കുക, മേശക്കടിയിൽ പിടിച്ചുനിൽക്കുക (കുനിയുക, തല മറയ്ക്കുക, പിടിക്കുക)',
          'ജനലുകൾ, ചില്ലുകൾ, വീഴാൻ സാധ്യതയുള്ള വസ്തുക്കൾ എന്നിവയിൽ നിന്ന് അകന്നുനിൽക്കുക',
          'പുറത്താണെങ്കിൽ കെട്ടിടങ്ങൾ, മരങ്ങൾ, വൈദ്യുത പോസ്റ്റുകൾ എന്നിവയിൽ നിന്ന് മാറുക',
          'ലിഫ്റ്റുകൾ ഉപയോഗിക്കരുത്; ഗോവണികൾ മാത്രം ഉപയോഗിക്കുക',
        ],
        afterTitle: 'ഭൂകമ്പത്തിന് ശേഷം:',
        after: [
          'പരിക്കേറ്റവർക്ക് പ്രഥമശുശ്രൂഷ നൽകുക',
          'ഗ്യാസ് ചോർച്ചയുണ്ടോ എന്ന് പരിശോധിക്കുക; മെഴുകുതിരിയോ തീപ്പെട്ടിയോ കത്തിക്കരുത്',
          'തുടർചലനങ്ങൾക്ക് സാധ്യതയുള്ളതിനാൽ ജാഗ്രത പാലിക്കുക',
          'റേഡിയോ വഴിയുള്ള ഔദ്യോഗിക നിർദ്ദേശങ്ങൾ പാലിക്കുക',
        ],
        officialResourcesTitle: 'ഔദ്യോഗിക വിവരങ്ങൾ:',
        resources: [
          { name: 'എൻ.ഡി.എം.എ ഭൂകമ്പ മാർഗ്ഗരേഖ', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'ഉരുൾപൊട്ടൽ & മണ്ണിടിച്ചിൽ',
        typeKey: 'landslide',
        severity: 'അതിതീവ്രം',
        beforeTitle: 'ഉരുൾപൊട്ടലിന് മുൻപ്:',
        before: [
          'മലയോര മേഖലകളിൽ ശക്തമായ മഴയുള്ളപ്പോൾ താഴ്വാരങ്ങളിൽ നിന്ന് സുരക്ഷിത സ്ഥാനത്തേക്ക് മാറുക',
          'മണ്ണൊലിപ്പ് തടയാൻ വൃക്ഷത്തൈകൾ വെച്ചുപിടിപ്പിക്കുകയും ഡ്രെയിനേജ് സുഗമമാക്കുകയും ചെയ്യുക',
          'മണ്ണിൽ വിള്ളലുകളോ മരങ്ങൾ ചരിയുന്നതോ ശ്രദ്ധയിൽപ്പെട്ടാൽ അധികൃതരെ അറിയിക്കുക',
          'രാത്രികാല യാത്രകൾ പൂർണ്ണമായും ഒഴിവാക്കുക',
        ],
        duringTitle: 'ഉരുൾപൊട്ടൽ സമയത്ത്:',
        during: [
          'മണ്ണിടിച്ചിലിന്റെ പാതയിൽ നിന്ന് ഉടൻ തന്നെ ഉയർന്ന പാറക്കെട്ടുകളിലേക്ക് മാറുക',
          'മരങ്ങൾ ഒടിയുന്ന ശബ്ദമോ അസാധാരണമായ മുഴക്കമോ കേട്ടാൽ സുരക്ഷിത സ്ഥാനത്തേക്ക് ഓടുക',
          'അയൽവാസികൾക്കും കുട്ടികൾക്കും വയോധികർക്കും മുന്നറിയിപ്പ് നൽകുക',
        ],
        afterTitle: 'ഉരുൾപൊട്ടലിന് ശേഷം:',
        after: [
          'ഇടിഞ്ഞുവീണ പ്രദേശങ്ങളിൽ പോകരുത്; വീണ്ടും മണ്ണിടിയാൻ സാധ്യതയുണ്ട്',
          'കുടുങ്ങിക്കിടക്കുന്നവരെ രക്ഷിക്കാൻ രക്ഷാപ്രവർത്തകരെ സഹായിക്കുക',
          'റോഡുകളിലെ തടസ്സങ്ങൾ നീക്കുന്നത് വരെ യാത്രകൾ ഒഴിവാക്കുക',
        ],
        officialResourcesTitle: 'ഔദ്യോഗിക വിവരങ്ങൾ:',
        resources: [
          { name: 'ജിയോളജിക്കൽ സർവേ ഓഫ് ഇന്ത്യ (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'ചുഴലിക്കാറ്റ് & കാറ്റും മഴയും',
        typeKey: 'cyclone',
        severity: 'തീവ്രം',
        beforeTitle: 'ചുഴലിക്കാറ്റിന് മുൻപ്:',
        before: [
          'കാലാവസ്ഥാ നിരീക്ഷണ കേന്ദ്രത്തിന്റെ (IMD) ബുള്ളറ്റിനുകൾ ശ്രദ്ധിക്കുക',
          'മേൽക്കൂരകളും അയഞ്ഞ ഷീറ്റുകളും ബലപ്പെടുത്തുക',
          'മൊബൈൽ ഫോണുകളും പവർ ബാങ്കുകളും ചാർജ് ചെയ്തു സൂക്ഷിക്കുക',
          'മത്സ്യബന്ധന തൊഴിലാളികൾ കടലിൽ പോകുന്നത് പൂർണ്ണമായി ഒഴിവാക്കുക',
        ],
        duringTitle: 'ചുഴലിക്കാറ്റ് സമയത്ത്:',
        during: [
          'ബലമുള്ള കോൺക്രീറ്റ് കെട്ടിടങ്ങൾക്കുള്ളിൽ തന്നെ കഴിയുക',
          'ജനലുകളും വാതിലുകളും അടച്ചുപൂട്ടുക',
          'കാറ്റിന്റെ വേഗത കുറഞ്ഞാലും പുറത്തിറങ്ങരുത്; കാറ്റിന്റെ കേന്ദ്രം കഴിഞ്ഞാൽ വീണ്ടും ശക്തിപ്രാപിക്കാം',
        ],
        afterTitle: 'ചുഴലിക്കാറ്റിന് ശേഷം:',
        after: [
          'പൊട്ടിവീണ വൈദ്യുത കമ്പികളിൽ സ്പർശിക്കരുത്',
          'ശുചിത്വമുള്ള കുടിവെള്ളം മാത്രം കുടിക്കുക',
          'വീണുകിടക്കുന്ന മരങ്ങൾ നീക്കാൻ ഫയർഫോഴ്സിനെ വിവരമറിയിക്കുക',
        ],
        officialResourcesTitle: 'ഔദ്യോഗിക വിവരങ്ങൾ:',
        resources: [
          { name: 'കേന്ദ്ര കാലാവസ്ഥാ വകുപ്പ് (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'തീപിടുത്തം & അഗ്നിബാധ',
        typeKey: 'fire',
        severity: 'ശ്രദ്ധിക്കുക',
        beforeTitle: 'തീപിടുത്തത്തിന് മുൻപ്:',
        before: [
          'വീടുകളിലും സ്ഥാപനങ്ങളിലും അഗ്നിശമന ഉപകരണങ്ങൾ കരുതുക',
          'തീപിടിക്കാൻ സാധ്യതയുള്ള വസ്തുക്കൾ ചൂടിൽ നിന്ന് മാറ്റി സൂക്ഷിക്കുക',
          'പുറത്തുകടക്കാനുള്ള എമർജൻസി വഴികൾ പരിശീലിക്കുക',
        ],
        duringTitle: 'തീപിടുത്ത സമയത്ത്:',
        during: [
          'ഉടൻ തന്നെ പുറത്തിറങ്ങുക; തിരികെ അകത്തേക്ക് കയറരുത്',
          'പുക കൂടുതലാണെങ്കിൽ നിലത്ത് ഇഴഞ്ഞുനീങ്ങുക (താഴ്ന്നു നീങ്ങുക)',
          'വസ്ത്രങ്ങളിൽ തീപിടിച്ചാൽ: നിൽക്കുക, നിലത്ത് കിടക്കുക, ഉരുളുക (നിൽക്കുക, നിലത്തു വീഴുക, ഉരുളുക)',
          'ഉടൻ തന്നെ 101 നമ്പറിൽ അഗ്നിശമന സേനയെ വിളിക്കുക',
        ],
        afterTitle: 'തീപിടുത്തത്തിന് ശേഷം:',
        after: [
          'അഗ്നിശമന ഉദ്യോഗസ്ഥർ സുരക്ഷിതമെന്ന് പ്രഖ്യാപിച്ച ശേഷം മാത്രം പ്രവേശിക്കുക',
          'പൊള്ളലേറ്റ ഭാഗങ്ങളിൽ തണുത്ത വെള്ളമൊഴിക്കുക; ഉടൻ ചികിത്സ തേടുക',
        ],
        officialResourcesTitle: 'ഔദ്യോഗിക വിവരങ്ങൾ:',
        resources: [
          { name: 'അഗ്നിശമന രക്ഷാ സേവന വകുപ്പ്', url: 'https://fire.kerala.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'പ്രധാന ദേശീയ പോർട്ടലുകൾ',
    additionalResources: [
      { name: 'ദേശീയ ദുരന്ത നിവാരണ അതോറിറ്റി (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'ദേശീയ ദുരന്ത പ്രതികരണ സേന (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'കേന്ദ്ര ജല കമ്മീഷൻ (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'ഇന്ത്യൻ സമുദ്ര വിവര കേന്ദ്രം (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  hi: {
    title: 'आपदा तैयारी एवं सुरक्षा दिशानिर्देश',
    subtitle: 'भारतीय सरकारी एजेंसियों के आधिकारिक सुरक्षा मानक',
    emergencyContactsTitle: 'आपातकालीन संपर्क नंबर',
    contacts: [
      { name: 'एनडीआरएफ हेल्पलाइन', number: '011-24363260', description: 'राष्ट्रीय आपदा प्रतिक्रिया बल' },
      { name: 'पुलिस सहायता', number: '100 / 112', description: 'आपातकालीन पुलिस सेवा' },
      { name: 'अग्निशमन सेवा', number: '101', description: 'आग बुझाने व बचाव सेवा' },
      { name: 'एम्बुलेंस सेवा', number: '102 / 108', description: 'चिकित्सा आपातकाल' },
      { name: 'आपदा प्रबंधन हेल्पलाइन', number: '1070 / 1078', description: 'राहत एवं बचाव कमान' },
      { name: 'महिला हेल्पलाइन', number: '1091', description: 'महिला सुरक्षा सहायता' },
    ],
    categories: [
      {
        disaster: 'बाढ़ सुरक्षा',
        typeKey: 'flood',
        severity: 'गंभीर',
        beforeTitle: 'बाढ़ से पहले:',
        before: [
          'अपने क्षेत्र के बाढ़ जोखिम और सुरक्षित निकासी मार्गों को जानें',
          'महत्वपूर्ण दस्तावेजों को वाटरप्रूफ बैग में सुरक्षित रखें',
          'पीने का पानी, सूखा राशन और प्राथमिक चिकित्सा किट ऊपरी मंजिलों पर रखें',
        ],
        duringTitle: 'बाढ़ के दौरान:',
        during: [
          'तुरंत ऊंचे स्थानों या राहत शिविरों की ओर जाएं',
          'बाढ़ के बहते पानी में चलने या गाड़ी चलाने की कोशिश न करें',
          'बिजली के खंभों और तारों से दूर रहें',
        ],
        afterTitle: 'बाढ़ के बाद:',
        after: [
          'प्रशासन द्वारा सुरक्षित घोषित किए जाने पर ही घर लौटें',
          'उबला हुआ या शुद्ध पानी ही पिएं',
          'क्षतिग्रस्त बिजली के तारों को न छुएं',
        ],
        officialResourcesTitle: 'आधिकारिक संसाधन:',
        resources: [
          { name: 'राष्ट्रीय आपदा प्रबंधन प्राधिकरण (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'भूकंप सुरक्षा',
        typeKey: 'earthquake',
        severity: 'उच्च',
        beforeTitle: 'भूकंप से पहले:',
        before: [
          'भारी फर्नीचर और अलमारियों को दीवारों से मजबूती से बांधें',
          'मजबूत मेज के नीचे सुरक्षित स्थान पहचानें',
          'आपातकालीन आपूर्ति किट तैयार रखें',
        ],
        duringTitle: 'भूकंप के दौरान:',
        during: [
          'झुकें, ढकें और पकड़ें (DROP, COVER, HOLD ON)',
          'खिड़कियों और गिरने वाली वस्तुओं से दूर रहें',
          'लिफ्ट का उपयोग न करें, सीढ़ियों का उपयोग करें',
        ],
        afterTitle: 'भूकंप के बाद:',
        after: [
          'घायलों को प्राथमिक उपचार दें',
          'गैस रिसाव की जांच करें, माचिस न जलाएं',
          'आफ्टरशॉक्स के लिए सतर्क रहें',
        ],
        officialResourcesTitle: 'आधिकारिक संसाधन:',
        resources: [
          { name: 'एनडीएमए भूकंप दिशानिर्देश', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'भूस्खलन सुरक्षा',
        typeKey: 'landslide',
        severity: 'गंभीर',
        beforeTitle: 'भूस्खलन से पहले:',
        before: [
          'पहाड़ी इलाकों में भारी बारिश के दौरान सतर्क रहें',
          'जल निकासी की उचित व्यवस्था रखें',
          'जमीन में दरार दिखने पर तुरंत इलाका खाली करें',
        ],
        duringTitle: 'भूस्खलन के दौरान:',
        during: [
          'मलबे के रास्ते से तुरंत दूर हटें',
          'पेड़ों के टूटने की आवाज सुनते ही ऊंचे स्थान पर जाएं',
        ],
        afterTitle: 'भूस्खलन के बाद:',
        after: [
          'प्रभावित क्षेत्र से दूर रहें, दोबारा मलबा गिरने का खतरा रहता है',
          'राहत एवं बचाव दल को सहयोग करें',
        ],
        officialResourcesTitle: 'आधिकारिक संसाधन:',
        resources: [
          { name: 'भारतीय भूवैज्ञानिक सर्वेक्षण (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'चक्रवात एवं तूफान',
        typeKey: 'cyclone',
        severity: 'उच्च',
        beforeTitle: 'चक्रवात से पहले:',
        before: [
          'मौसम विभाग (IMD) की चेतावनियों पर ध्यान दें',
          'खिड़कियों और दरवाजों को सुरक्षित रूप से बंद करें',
          'मछुआरों को समुद्र में जाने से रोकें',
        ],
        duringTitle: 'चक्रवात के दौरान:',
        during: [
          'पक्के मकान के सुरक्षित कमरे में रहें',
          'हवा थमने पर भी तुरंत बाहर न निकलें',
        ],
        afterTitle: 'चक्रवात के बाद:',
        after: [
          'टूटे बिजली के तारों से दूर रहें',
          'शुद्ध पानी का उपयोग करें',
        ],
        officialResourcesTitle: 'आधिकारिक संसाधन:',
        resources: [
          { name: 'भारत मौसम विज्ञान विभाग (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'अग्नि सुरक्षा',
        typeKey: 'fire',
        severity: 'मध्यम',
        beforeTitle: 'आग लगने से पहले:',
        before: [
          'अग्निशामक यंत्र चालू स्थिति में रखें',
          'आपातकालीन निकास मार्ग हमेशा साफ रखें',
        ],
        duringTitle: 'आग लगने पर:',
        during: [
          'तुरंत सुरक्षित बाहर निकलें, वापस अंदर न जाएं',
          'धुआं होने पर फर्श पर रेंगते हुए निकलें',
          'कपड़ों में आग लगने पर: रुकें, झुकें और लुढ़कें (STOP, DROP, ROLL)',
        ],
        afterTitle: 'आग बुझने के बाद:',
        after: [
          'फायर ब्रिगेड की अनुमति के बाद ही घर में प्रवेश करें',
          'जले हुए स्थान पर ठंडा पानी डालें',
        ],
        officialResourcesTitle: 'आधिकारिक संसाधन:',
        resources: [
          { name: 'फायर सर्विसेज पोर्टल', url: 'https://www.ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'अतिरिक्त राष्ट्रीय संसाधन',
    additionalResources: [
      { name: 'राष्ट्रीय आपदा प्रबंधन प्राधिकरण (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'राष्ट्रीय आपदा प्रतिक्रिया बल (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'केंद्रीय जल आयोग (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'भारतीय राष्ट्रीय महासागर सूचना सेवा केंद्र (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  // English fallback template (used for 'en' and fallback structure)
  en: {
    title: 'Disaster Preparedness Guidelines',
    subtitle: 'Official guidelines from Indian government disaster management agencies',
    emergencyContactsTitle: 'Emergency Contacts',
    contacts: [
      { name: 'NDRF Helpline', number: '011-24363260', description: 'National Disaster Response Force' },
      { name: 'Police Emergency', number: '100 / 112', description: 'Police assistance' },
      { name: 'Fire Brigade', number: '101', description: 'Fire & rescue emergency' },
      { name: 'Ambulance', number: '102 / 108', description: 'Medical emergency' },
      { name: 'Disaster Helpline', number: '1070 / 1078', description: 'National disaster helpline' },
      { name: 'Women Helpline', number: '1091', description: 'Women safety emergency' },
    ],
    categories: [
      {
        disaster: 'Flood Safety',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'Before Flood:',
        before: [
          'Know your local flood risk and designated evacuation routes',
          'Keep vital documents sealed in waterproof pouches',
          'Stock drinking water, dry rations, and trauma kits on elevated floors',
        ],
        duringTitle: 'During Flood:',
        during: [
          'Evacuate immediately to higher ground or relief centers',
          'Never walk, swim, or drive through moving water',
          'Stay clear of submerged power lines and electric poles',
        ],
        afterTitle: 'After Flood:',
        after: [
          'Return home only after authorities issue all-clear clearance',
          'Drink only boiled or purified water',
          'Avoid contaminated flood debris and report broken utility lines',
        ],
        officialResourcesTitle: 'Official Resources:',
        resources: [
          { name: 'National Disaster Management Authority (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'Earthquake Safety',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'Before Earthquake:',
        before: [
          'Fasten heavy shelves and appliances to structural walls',
          'Identify safe drop zones under heavy tables or interior walls',
          'Keep an emergency supplies kit ready with a flashlight',
        ],
        duringTitle: 'During Earthquake:',
        during: [
          'DROP, COVER, and HOLD ON under a sturdy table or desk',
          'Stay clear of glass windows, exterior walls, and falling objects',
          'Do not use elevators; use designated fire stairwells',
        ],
        afterTitle: 'After Earthquake:',
        after: [
          'Check for injuries and provide immediate first aid',
          'Inspect premises for gas leaks; do not strike matches',
          'Anticipate aftershocks and remain in open safe clearings',
        ],
        officialResourcesTitle: 'Official Resources:',
        resources: [
          { name: 'NDMA Earthquake Guidelines', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'Landslide Safety',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'Before Landslide:',
        before: [
          'Learn historical landslide hazard zones in hill areas',
          'Plant native ground-cover vegetation to secure slope soil',
          'Evacuate low valleys during intense monsoon cloudbursts',
        ],
        duringTitle: 'During Landslide:',
        during: [
          'Move away from the path of debris flow immediately',
          'Listen for unusual rumbling sounds or cracking trees',
        ],
        afterTitle: 'After Landslide:',
        after: [
          'Stay away from the slide area; subsequent collapses can follow',
          'Aid rescue crews in locating isolated households',
        ],
        officialResourcesTitle: 'Official Resources:',
        resources: [
          { name: 'Geological Survey of India (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'Cyclone Safety',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'Before Cyclone:',
        before: [
          'Monitor Indian Meteorological Department (IMD) advisories',
          'Secure loose roof sheets, solar panels, and outdoor items',
          'Ensure fishermen strictly heed coastal departure bans',
        ],
        duringTitle: 'During Cyclone:',
        during: [
          'Remain inside sturdy concrete structures away from windows',
          'Do not venture out during the false calm of the storm eye',
        ],
        afterTitle: 'After Cyclone:',
        after: [
          'Beware of downed live electrical cables and fallen trees',
          'Consume only verified potable boiled water',
        ],
        officialResourcesTitle: 'Official Resources:',
        resources: [
          { name: 'India Meteorological Department (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'Fire Safety',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'Before Fire:',
        before: [
          'Install smoke alarms and inspect electrical wirings periodically',
          'Keep portable fire extinguishers at easily accessible locations',
          'Identify and practice multiple emergency exit pathways',
        ],
        duringTitle: 'During Fire:',
        during: [
          'Evacuate immediately without pausing to collect belongings',
          'Crawl low under smoke toward nearest clear exit',
          'If clothes catch fire: Stop, Drop, and Roll',
          'Dial 101 to alert fire and rescue services immediately',
        ],
        afterTitle: 'After Fire:',
        after: [
          'Re-enter building only after fire service personnel declare safe',
          'Apply cool water to burns and seek prompt medical attention',
        ],
        officialResourcesTitle: 'Official Resources:',
        resources: [
          { name: 'Directorate General Fire Services (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'Additional National Resources',
    additionalResources: [
      { name: 'National Disaster Management Authority (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'National Disaster Response Force (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'Central Water Commission (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'Indian National Centre for Ocean Information Services (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  ta: {
    title: 'பேரிடர் தயார்நிலை வழிகாட்டுதல்கள்',
    subtitle: 'இந்திய அரசு பேரிடர் மேலாண்மை முகமைகளின் அதிகாரப்பூர்வ வழிகாட்டுதல்கள்',
    emergencyContactsTitle: 'அவசரகால உதவி எண்கள்',
    contacts: [
      { name: 'NDRF உதவி மையம்', number: '011-24363260', description: 'தேசிய பேரிடர் மீட்புப் படை' },
      { name: 'காவல்துறை', number: '100 / 112', description: 'அவசர காவல் உதவி' },
      { name: 'தீயணைப்பு & மீட்பு', number: '101', description: 'தீயணைப்பு மற்றும் மீட்பு சேவை' },
      { name: 'ஆம்புலன்ஸ் சேவை', number: '102 / 108', description: 'அவசர மருத்துவ சேவை' },
      { name: 'பேரிடர் உதவி மையம்', number: '1070 / 1078', description: 'மாநில அவசரகால செயல்பாட்டு மையம்' },
      { name: 'பெண்கள் உதவி மையம்', number: '1091', description: 'பெண்கள் பாதுகாப்பு உதவி' },
    ],
    categories: [
      {
        disaster: 'வெள்ளப் பெருக்கு பாதுகாப்பு',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'வெள்ளத்திற்கு முன்:',
        before: [
          'உங்கள் பகுதியின் வெள்ள அபாயங்களையும் வெளியேறும் வழிகளையும் அறிந்து கொள்ளுங்கள்',
          'முக்கிய ஆவணங்களை நீர்ப்புகா பைகளில் பத்திரமாக வைக்கவும்',
          'குடிநீர், உலர் உணவுகள் மற்றும் முதலுதவி பெட்டிகளை மேல் தளங்களில் வைக்கவும்',
        ],
        duringTitle: 'வெள்ளத்தின் போது:',
        during: [
          'உடனடியாக உயரமான இடங்களுக்கோ நிவாரண முகாம்களுக்கோ செல்லவும்',
          'நகரும் வெள்ள நீரில் நடக்கவோ, நீந்தவோ அல்லது வாகனம் ஓட்டவோ வேண்டாம்',
          'நீரில் மூழ்கிய மின்கம்பங்கள் மற்றும் மின் கம்பிகளிலிருந்து விலகி இருங்கள்',
        ],
        afterTitle: 'வெள்ளத்திற்குப் பின்:',
        after: [
          'அதிகாரிகள் அனுமதி அளித்த பின்னரே வீட்டிற்குத் திரும்பவும்',
          'காய்ச்சிய அல்லது சுத்திகரிக்கப்பட்ட தண்ணீரை மட்டுமே குடிக்கவும்',
          'சேதமடைந்த மின் கம்பிகளைத் தொடாதீர்கள்; புகாரளிக்கவும்',
        ],
        officialResourcesTitle: 'அதிகாரப்பூர்வ தகவல்கள்:',
        resources: [
          { name: 'தேசிய பேரிடர் மேலாண்மை ஆணையம் (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'நிலநடுக்க பாதுகாப்பு',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'நிலநடுக்கத்திற்கு முன்:',
        before: [
          'கனமான அலமாரிகள் மற்றும் உபகரணங்களை சுவரில் உறுதியாக பொருத்தவும்',
          'வலுவான மேசைகளின் கீழ் பாதுகாப்பான இடங்களை அடையாளம் காணவும்',
          'அவசரகால பொருட்கள் அடங்கிய பெட்டியை எப்போதும் தயாராக வைக்கவும்',
        ],
        duringTitle: 'நிலநடுக்கத்தின் போது:',
        during: [
          'குனியவும், மறைந்து கொள்ளவும், பிடித்துக் கொள்ளவும் (DROP, COVER, HOLD ON)',
          'ஜன்னல்கள், கண்ணாடி மற்றும் விழக்கூடிய பொருட்களிலிருந்து விலகி இருங்கள்',
          'மின்தூக்கிகளைப் (லிஃப்ட்) பயன்படுத்த வேண்டாம்; படிக்கட்டுகளைப் பயன்படுத்தவும்',
        ],
        afterTitle: 'நிலநடுக்கத்திற்குப் பின்:',
        after: [
          'காயமடைந்தவர்களுக்கு முதலுதவி அளிக்கவும்',
          'எரிவாயு கசிவு உள்ளதா என சோதிக்கவும்; தீக்குச்சிகளை கொளுத்த வேண்டாம்',
          'தொடர் நடுக்கங்கள் ஏற்படும் வாய்ப்பு இருப்பதால் கவனமாக இருக்கவும்',
        ],
        officialResourcesTitle: 'அதிகாரப்பூர்வ தகவல்கள்:',
        resources: [
          { name: 'NDMA நிலநடுக்க வழிகாட்டுதல்கள்', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'நிலச்சரிவு பாதுகாப்பு',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'நிலச்சரிவுக்கு முன்:',
        before: [
          'மலைப்பகுதிகளில் நிலச்சரிவு அபாய பகுதிகளை அறிந்துகொள்ளவும்',
          'மண்ணரிப்பைத் தடுக்க வடிகால்களை சுத்தமாகவும் மரங்களை வளர்க்கவும்',
          'கடும் மழையின் போது தாழ்வான பள்ளத்தாக்குகளிலிருந்து வெளியேறவும்',
        ],
        duringTitle: 'நிலச்சரிவின் போது:',
        during: [
          'இடிபாடுகள் சரியும் பாதையிலிருந்து உடனடியாக விலகி ஓடவும்',
          'மரங்கள் முறியும் அல்லது உருளும் விசித்திரமான சத்தங்களை கவனிக்கவும்',
        ],
        afterTitle: 'நிலச்சரிவுக்குப் பின்:',
        after: [
          'சரிவு பகுதிக்கு அருகில் செல்ல வேண்டாம்; மீண்டும் சரிய வாய்ப்புள்ளது',
          'பாதிக்கப்பட்ட மக்களை மீட்க மீட்புக் குழுவினருக்கு உதவவும்',
        ],
        officialResourcesTitle: 'அதிகாரப்பூர்வ தகவல்கள்:',
        resources: [
          { name: 'இந்திய புவியியல் ஆய்வு மையம் (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'புயல் பாதுகாப்பு',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'புயலுக்கு முன்:',
        before: [
          'வானிலை ஆய்வு மையத்தின் (IMD) எச்சரிக்கைகளைக் கவனியுங்கள்',
          'கூரைத் தகடுகள் மற்றும் வெளிப்புறப் பொருட்களைப் பலப்படுத்தவும்',
          'மீனவர்கள் கடலுக்குச் செல்வதை முற்றிலும் தவிர்க்கவும்',
        ],
        duringTitle: 'புயலின் போது:',
        during: [
          'வலுவான கான்கிரீட் கட்டிடங்களுக்குள் ஜன்னல்களிலிருந்து தள்ளி இருக்கவும்',
          'புயலின் கண் பகுதி கடக்கும் அமைதியான நேரத்தில் வெளியே செல்ல வேண்டாம்',
        ],
        afterTitle: 'புயலுக்குப் பின்:',
        after: [
          'அறுந்து கிடக்கும் மின்கம்பிகளைத் தொடாதீர்கள்',
          'கொதிக்க வைத்த குடிநீரை மட்டுமே அருந்தவும்',
        ],
        officialResourcesTitle: 'அதிகாரப்பூர்வ தகவல்கள்:',
        resources: [
          { name: 'இந்திய வானிலை ஆய்வு மையம் (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'தீ விபத்து பாதுகாப்பு',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'தீ விபத்துக்கு முன்:',
        before: [
          'வீடுகளிலும் அலுவலகங்களிலும் தீயணைப்பு கருவிகளை வைக்கவும்',
          'அவசர வெளியேறும் வழிகளில் தடைகள் இல்லாமல் பார்த்துக் கொள்ளவும்',
          'குடும்பத்தினருடன் வெளியேறும் வழிகளை பயிற்சி செய்யவும்',
        ],
        duringTitle: 'தீ விபத்தின் போது:',
        during: [
          'உடமைகளை எடுக்காமல் உடனடியாக வெளியேறவும்',
          'புகை இருந்தால் தரை வழியாக ஊர்ந்து செல்லவும்',
          'ஆடையில் தீ பிடித்தால்: நில்லுங்கள், விழுங்கள், உருளுங்கள்',
          'உடனடியாக 101 தீயணைப்பு துறைக்கு அழைக்கவும்',
        ],
        afterTitle: 'தீ விபத்துக்குப் பின்:',
        after: [
          'அதிகாரிகள் பாதுகாப்பானது என அறிவிக்கும் வரை உள்ளே செல்ல வேண்டாம்',
          'தீக்காயங்களுக்கு குளிர்ந்த நீரை ஊற்றி உடனடியாக மருத்துவ உதவி பெறவும்',
        ],
        officialResourcesTitle: 'அதிகாரப்பூர்வ தகவல்கள்:',
        resources: [
          { name: 'தீயணைப்பு சேவைகள் போர்டல்', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'கூடுதல் தேசிய ஆதாரங்கள்',
    additionalResources: [
      { name: 'தேசிய பேரிடர் மேலாண்மை ஆணையம் (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'தேசிய பேரிடர் மீட்புப் படை (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'மத்திய நீர் ஆணையம் (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'இந்திய கடல்சார் தகவல் மையம் (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  te: {
    title: 'విపత్తు సంసిద్ధత మార్గదర్శకాలు',
    subtitle: 'భారత ప్రభుత్వ విపత్తు నిర్వహణ సంస్థల అధికారిక భద్రతా ప్రమాణాలు',
    emergencyContactsTitle: 'అత్యవసర సంప్రదింపు నంబర్లు',
    contacts: [
      { name: 'NDRF హెల్ప్‌లైన్', number: '011-24363260', description: 'జాతీయ విపత్తు ప్రతిస్పందన దళం' },
      { name: 'పోలీస్ కంట్రోల్ రూమ్', number: '100 / 112', description: 'అత్యవసర పోలీసు సేవ' },
      { name: 'ఫైర్ బ్రిగేడ్', number: '101', description: 'అగ్నిమాపక మరియు రక్షణ సేవ' },
      { name: 'అంబులెన్స్', number: '102 / 108', description: 'వైద్య అత్యవసర సేవ' },
      { name: 'విపత్తు హెల్ప్‌లైన్', number: '1070 / 1078', description: 'జాతీయ విపత్తు హెల్ప్‌లైన్' },
      { name: 'మహిళా హెల్ప్‌లైన్', number: '1091', description: 'మహిళా భద్రతా సేవ' },
    ],
    categories: [
      {
        disaster: 'వరద భద్రత',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'వరదలకు ముందు:',
        before: [
          'మీ ప్రాంతంలోని వరద ముప్పు మరియు సురక్షిత తరలింపు మార్గాలను తెలుసుకోండి',
          'ముఖ్యమైన పత్రాలను వాటర్‌ప్రూఫ్ సంచులలో భద్రపరచండి',
          'తాగునీరు, పొడి ఆహారం, ప్రథమ చికిత్స వస్తువులను ఎత్తైన ప్రదేశాలలో ఉంచండి',
        ],
        duringTitle: 'వరదల సమయంలో:',
        during: [
          'వెంటనే ఎత్తైన ప్రాంతాలకు లేదా పునరావాస కేంద్రాలకు వెళ్లండి',
          'వరద ప్రవాహంలో నడవకండి లేదా వాహనాలు నడపకండి',
          'విద్యుత్ స్తంభాలు, తెగిపడిన తీగలకు దూరంగా ఉండండి',
        ],
        afterTitle: 'వరదల తరువాత:',
        after: [
          'అధికారులు సురక్షితమని ప్రకటించిన తర్వాతే ఇళ్లకు తిరిగి రండి',
          'కాచి చల్లార్చిన నీటిని మాత్రమే తాగండి',
          'దెబ్బతిన్న విద్యుత్ వైర్లను ముట్టుకోవద్దు',
        ],
        officialResourcesTitle: 'అధికారిక వనరులు:',
        resources: [
          { name: 'జాతీయ విపత్తు నిర్వహణ సంస్థ (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'భూకంప భద్రత',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'భూకంపానికి ముందు:',
        before: [
          'భారీ వస్తువులు, అల్మారాలను గోడలకు దృఢంగా అమర్చండి',
          'బలమైన బల్లల కింద సురక్షిత స్థలాలను గుర్తించండి',
          'అత్యవసర వస్తువుల కిట్‌ను సిద్ధంగా ఉంచుకోండి',
        ],
        duringTitle: 'భూకంపం సమయంలో:',
        during: [
          'వంగండి, తల దాచుకోండి, పట్టుకోండి (DROP, COVER, HOLD ON)',
          'కిటికీలు, అద్దాలు మరియు పడిపోయే వస్తువులకు దూరంగా ఉండండి',
          'లిఫ్ట్‌లను ఉపయోగించవద్దు; మెట్లను మాత్రమే ఉపయోగించండి',
        ],
        afterTitle: 'భూకంపం తరువాత:',
        after: [
          'గాయపడిన వారికి ప్రథమ చికిత్స అందించండి',
          'గ్యాస్ లీకేజీలను తనిఖీ చేయండి; అగ్గిపెట్టెలు వెలిగించవద్దు',
          'తదుపరి ప్రకంపనలు (ఆఫ్టర్‌షాక్‌లు) వచ్చే అవకాశం ఉన్నందున జాగ్రత్తగా ఉండండి',
        ],
        officialResourcesTitle: 'అధికారిక వనరులు:',
        resources: [
          { name: 'NDMA భూకంప మార్గదర్శకాలు', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'కొండచరియలు విరిగిపడటం',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'కొండచరియలకు ముందు:',
        before: [
          'కొండ ప్రాంతాలలో ప్రమాదకర ప్రాంతాల చరిత్రను తెలుసుకోండి',
          'నేల కోతను నివారించడానికి మొక్కలు నాటండి, మురుగు కాలువలను సరిగ్గా ఉంచండి',
          'భారీ వర్షాల సమయంలో లోతైన లోయల నుండి సురక్షిత ప్రాంతాలకు వెళ్లండి',
        ],
        duringTitle: 'కొండచరియల సమయంలో:',
        during: [
          'శిథిలాలు పడే మార్గం నుండి వెంటనే దూరంగా వెళ్ళండి',
          'చెట్లు విరిగిపడే శబ్దాలు లేదా వింత శబ్దాలను వినండి',
        ],
        afterTitle: 'కొండచరియల తరువాత:',
        after: [
          'ప్రమాద స్థలానికి వెళ్లవద్దు; మళ్లీ విరిగిపడే ప్రమాదం ఉంది',
          'సహాయక చర్యలలో సిబ్బందికి సహాయపడండి',
        ],
        officialResourcesTitle: 'అధికారిక వనరులు:',
        resources: [
          { name: 'జియోలాజికల్ సర్వే ఆఫ్ ఇండియా (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'తుఫాను భద్రత',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'తుఫానుకు ముందు:',
        before: [
          'భారత వాతావరణ శాఖ (IMD) సమాచారాన్ని నిరంతరం గమనించండి',
          'పైకప్పు రేకులు, ఇతర వదులుగా ఉన్న వస్తువులను భద్రపరచండి',
          'మత్స్యకారులు సముద్రంలోకి వెళ్లకూడదు',
        ],
        duringTitle: 'తుఫాను సమయంలో:',
        during: [
          'పటిష్టమైన భవనాలలో ఉండండి, కిటికీలకు దూరంగా ఉండండి',
          'తుఫాను ప్రశాంతంగా అనిపించినప్పుడు బయటకు రావద్దు',
        ],
        afterTitle: 'తుఫాను తరువాత:',
        after: [
          'తెగిపడిన విద్యుత్ తీగలు, నేలకూలిన చెట్ల పట్ల జాగ్రత్తగా ఉండండి',
          'కాచి చల్లార్చిన నీటిని మాత్రమే త్రాగండి',
        ],
        officialResourcesTitle: 'అధికారిక వనరులు:',
        resources: [
          { name: 'భారత వాతావరణ శాఖ (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'అగ్ని ప్రమాద భద్రత',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'అగ్ని ప్రమాదానికి ముందు:',
        before: [
          'అగ్నిమాపక పరికరాలను అందుబాటులో ఉంచుకోండి',
          'అత్యవసర నిష్క్రమణ మార్గాలను ఎల్లప్పుడూ ఖాళీగా ఉంచండి',
          'కుటుంబ సభ్యులతో బయటకు వెళ్లే మార్గాలను అభ్యసించండి',
        ],
        duringTitle: 'అగ్ని ప్రమాదం సమయంలో:',
        during: [
          'వస్తువుల కోసం ఆగకుండా వెంటనే బయటకు రండి',
          'పొగ ఉంటే నేలపై పాకుతూ వెళ్ళండి',
          'బట్టలకు నిప్పు అంటుకుంటే: ఆగండి, పడుకోండి, దొర్లండి (STOP, DROP, ROLL)',
          'వెంటనే 101 కు కాల్ చేసి సమాచారం ఇవ్వండి',
        ],
        afterTitle: 'అగ్ని ప్రమాదం తరువాత:',
        after: [
          'అధికారుల అనుమతి తర్వాతే ఇంట్లోకి ప్రవేశించండి',
          'కాలిన గాయాలపై చల్లని నీరు పోసి వెంటనే వైద్య సహాయం పొందండి',
        ],
        officialResourcesTitle: 'అధికారిక వనరులు:',
        resources: [
          { name: 'NDMA ఫైర్ సర్వీసెస్', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'అదనపు జాతీయ వనరులు',
    additionalResources: [
      { name: 'జాతీయ విపత్తు నిర్వహణ సంస్థ (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'జాతీయ విపత్తు ప్రతిస్పందన దళం (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'సెంట్రల్ వాటర్ కమిషన్ (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'ఇండియన్ నేషనల్ సెంటర్ ఫర్ ఓషన్ ఇన్ఫర్మేషన్ సర్వీసెస్ (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  mr: {
    title: 'आपत्ती व्यवस्थापन व सुरक्षा मार्गदर्शक तत्त्वे',
    subtitle: 'भारतीय सरकारी आपत्ती व्यवस्थापन संस्थांची अधिकृत मार्गदर्शक तत्त्वे',
    emergencyContactsTitle: 'आपत्कालीन संपर्क क्रमांक',
    contacts: [
      { name: 'NDRF हेल्पलाइन', number: '011-24363260', description: 'राष्ट्रीय आपत्ती प्रतिसाद दल' },
      { name: 'पोलीस नियंत्रण कक्ष', number: '100 / 112', description: 'आपत्कालीन पोलीस मदत' },
      { name: 'अग्निशामक दल', number: '101', description: 'आग व बचाव सेवा' },
      { name: 'रुग्णवाहिका', number: '102 / 108', description: 'वैद्यकीय आणीबाणी' },
      { name: 'आपत्ती नियंत्रण कक्ष', number: '1070 / 1078', description: 'राज्य आपत्ती व्यवस्थापन' },
      { name: 'महिला हेल्पलाइन', number: '1091', description: 'महिला सुरक्षा मदत' },
    ],
    categories: [
      {
        disaster: 'पूर सुरक्षा',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'पुरापूर्वी:',
        before: [
          'आपल्या भागातील पुराचा धोका व सुरक्षित स्थलांतर मार्ग जाणून घ्या',
          'महत्त्वाची कागदपत्रे वॉटरप्रूफ पिशवीत ठेवा',
          'पिण्याचे पाणी, सुका खाऊ व प्रथमोपचार साहित्य उंचावर ठेवा',
        ],
        duringTitle: 'पुरादरम्यान:',
        during: [
          'त्वरित उंचावरील ठिकाणी किंवा मदत शिबिरांमध्ये जा',
          'पुराच्या पाण्यात चालणे किंवा वाहन चालवणे टाळा',
          'विजेचे खांब आणि तुटलेल्या तारांपासून लांब राहा',
        ],
        afterTitle: 'पुरानंतर:',
        after: [
          'प्रशासनाने सुरक्षित घोषित केल्यावरच घरी परता',
          'उकळलेले किंवा शुद्ध पाणीच प्या',
          'विजेच्या उपकरणांना हात लावू नका',
        ],
        officialResourcesTitle: 'अधिकृत स्रोत:',
        resources: [
          { name: 'राष्ट्रीय आपत्ती व्यवस्थापन प्राधिकरण (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'भूकंप सुरक्षा',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'भूकंपापूर्वी:',
        before: [
          'जड कपाटे व वस्तू भिंतीला घट्ट बसवा',
          'मजबूत टेबलाखाली सुरक्षित जागा निश्चित करा',
          'आपत्कालीन किट तयार ठेवा',
        ],
        duringTitle: 'भूकंपादरम्यान:',
        during: [
          'खाली बसा, डोके झाका व घट्ट धरा (DROP, COVER, HOLD ON)',
          'खिडक्या आणि काचेच्या वस्तूंपासून दूर राहा',
          'लिफ्टचा वापर करू नका; जिन्याचा वापर करा',
        ],
        afterTitle: 'भूकंपानंतर:',
        after: [
          'जखमींना प्रथमोपचार द्या',
          'गॅस गळती तपासा; आगपेटी पेटवू नका',
          'पुन्हा धक्के बसण्याची शक्यता असल्याने सावध राहा',
        ],
        officialResourcesTitle: 'अधिकृत स्रोत:',
        resources: [
          { name: 'NDMA भूकंप मार्गदर्शक तत्त्वे', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'भूस्खलन सुरक्षा',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'भूस्खलनापूर्वी:',
        before: [
          'डोंगराळ भागातील भूस्खलन प्रवण क्षेत्र ओळखा',
          'मातीची धूप थांबवण्यासाठी झाडे लावा व निचरा व्यवस्था नीट ठेवा',
          'मुसळधार पावसात दऱ्याखोऱ्यांतून सुरक्षित स्थळी जा',
        ],
        duringTitle: 'भूस्खलनादरम्यान:',
        during: [
          'दरड कोसळण्याच्या मार्गावरून त्वरित दूर व्हा',
          'झाडे मोडण्याचे किंवा असामान्य आवाज ऐकून सावध व्हा',
        ],
        afterTitle: 'भूस्खलनानंतर:',
        after: [
          'घसरण झालेल्या भागाजवळ जाऊ नका; पुन्हा दरड कोसळू शकते',
          'बचाव पथकाला अडकलेल्या लोकांना शोधण्यात मदत करा',
        ],
        officialResourcesTitle: 'अधिकृत स्रोत:',
        resources: [
          { name: 'भारतीय भूवैज्ञानिक सर्वेक्षण (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'चक्रीवादळ सुरक्षा',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'चक्रीवादळापूर्वी:',
        before: [
          'हवामान खात्याच्या (IMD) सूचनांचे नियमित पालन करा',
          'घराचे पत्रे व बाहेरील वस्तू सुरक्षित बांधून ठेवा',
          'मासेमारांनी समुद्रात जाणे पूर्णपणे टाळावे',
        ],
        duringTitle: 'चक्रीवादळादरम्यान:',
        during: [
          'मजबूत कॉंक्रिटच्या इमारतीत खिडक्यांपासून दूर राहा',
          'वादळाच्या केंद्रस्थानी वारा मंदावला तरी बाहेर पडू नका',
        ],
        afterTitle: 'चक्रीवादळानंतर:',
        after: [
          'तुटलेल्या विजेच्या तारा व पडलेल्या झाडांपासून सावध राहा',
          'फक्त उकळलेले पाणी प्या',
        ],
        officialResourcesTitle: 'अधिकृत स्रोत:',
        resources: [
          { name: 'भारतीय हवामान विभाग (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'आग सुरक्षा',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'आगीपूर्वी:',
        before: [
          'अग्निशामक यंत्रणा चालू स्थितीत ठेवा',
          'आपत्कालीन निकास मार्ग मोकळा ठेवा',
          'घरातील सदस्यांसोबत बाहेर पडण्याचा सराव करा',
        ],
        duringTitle: 'आग लागल्यावर:',
        during: [
          'वस्तू गोळा न करता त्वरित बाहेर पडा',
          'धूर असल्यास जमिनीवर रांगत बाहेर पडा',
          'कपड्यांना आग लागल्यास: थांबा, खाली पडा आणि लोळा (STOP, DROP, ROLL)',
          'त्वरित 101 वर फोन करून अग्निशामक दलाला बोलवा',
        ],
        afterTitle: 'आगीनंतर:',
        after: [
          'अग्निशामक दलाने परवानगी दिल्यावरच घरात प्रवेश करा',
          'भाजलेल्या जागेवर थंड पाणी टाका व डॉक्टरी मदत घ्या',
        ],
        officialResourcesTitle: 'अधिकृत स्रोत:',
        resources: [
          { name: 'अग्निशमन सेवा पोर्टल (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'अतिरिक्त राष्ट्रीय संसाधने',
    additionalResources: [
      { name: 'राष्ट्रीय आपत्ती व्यवस्थापन प्राधिकरण (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'राष्ट्रीय आपत्ती प्रतिसाद दल (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'केंद्रीय जल आयोग (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'भारतीय राष्ट्रीय महासागर सूचना सेवा केंद्र (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  gu: {
    title: 'આપત્તિ સજ્જતા અને સુરક્ષા માર્ગદર્શિકા',
    subtitle: 'ભારતીય સરકારી આપત્તિ વ્યવસ્થાપન એજન્સીઓની સત્તાવાર માર્ગદર્શિકા',
    emergencyContactsTitle: 'કટોકટી સંપર્ક નંબરો',
    contacts: [
      { name: 'NDRF હેલ્પલાઇન', number: '011-24363260', description: 'રાષ્ટ્રીય આપત્તિ પ્રતિભાવ દળ' },
      { name: 'પોલીસ કંટ્રોલ રૂમ', number: '100 / 112', description: 'કટોકટી પોલીસ સહાય' },
      { name: 'અગ્નિશામક સેવા', number: '101', description: 'આગ અને બચાવ કામગીરી' },
      { name: 'એમ્બ્યુલન્સ', number: '102 / 108', description: 'તબીબી કટોકટી સેવા' },
      { name: 'આપત્તિ હેલ્પલાઇન', number: '1070 / 1078', description: 'રાજ્ય આપત્તિ વ્યવસ્થાપન' },
      { name: 'મહિલા હેલ્પલાઇન', number: '1091', description: 'મહિલા સુરક્ષા હેલ્પલાઇન' },
    ],
    categories: [
      {
        disaster: 'પૂર સુરક્ષા',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'પૂર પહેલાં:',
        before: [
          'તમારા વિસ્તારનું પૂર જોખમ અને સુરક્ષિત સ્થળાંતર માર્ગો જાણો',
          'મહત્વપૂર્ણ દસ્તાવેજો વોટરપ્રૂફ બેગમાં રાખો',
          'પીવાનું પાણી, સૂકો ખોરાક અને પ્રાથમિક સારવાર કીટ ઊંચા સ્થળે રાખો',
        ],
        duringTitle: 'પૂર દરમિયાન:',
        during: [
          'તાત્કાલિક ઊંચા સ્થળોએ અથવા રાહત શિબિરોમાં જાઓ',
          'વહેતા પૂરના પાણીમાં ચાલવું કે વાહન ચલાવવું નહીં',
          'વીજળીના થાંભલાઓ અને તૂટેલા વાયરોથી દૂર રહો',
        ],
        afterTitle: 'પૂર પછી:',
        after: [
          'સત્તાવાળાઓ સુરક્ષિત જાહેર કરે પછી જ ઘરે પાછા ફરો',
          'ઉકાળેલું અથવા શુદ્ધ કરેલું પાણી જ પીવો',
          'ક્ષતિગ્રસ્ત વીજ વાયરોને અડશો નહીં',
        ],
        officialResourcesTitle: 'સત્તાવાર સંસાધનો:',
        resources: [
          { name: 'રાષ્ટ્રીય આપત્તિ વ્યવસ્થાપન સત્તામંડળ (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'ધરતીકંપ સુરક્ષા',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'ધરતીકંપ પહેલાં:',
        before: [
          'ભારે કબાટો અને ઉપકરણોને દિવાલ સાથે મજબૂત રીતે બાંધો',
          'મજબૂત ટેબલ નીચે સુરક્ષિત જગ્યા ઓળખો',
          'કટોકટીની કીટ હંમેશા તૈયાર રાખો',
        ],
        duringTitle: 'ધરતીકંપ દરમિયાન:',
        during: [
          'નીચે નમો, ઢાંકો અને પકડી રાખો (DROP, COVER, HOLD ON)',
          'બારીઓ અને કાચની વસ્તુઓથી દૂર રહો',
          'લિફ્ટનો ઉપયોગ ન કરવો; સીડીનો ઉપયોગ કરો',
        ],
        afterTitle: 'ધરતીકંપ પછી:',
        after: [
          'ઇજાગ્રસ્તોને પ્રાથમિક સારવાર આપો',
          'ગેસ લિકેજ તપાસો; દીવાસળી ન સળગાવો',
          'આફ્ટરશોક્સ આવવાની શક્યતા હોવાથી સાવચેત રહો',
        ],
        officialResourcesTitle: 'સત્તાવાર સંસાધનો:',
        resources: [
          { name: 'NDMA ધરતીકંપ માર્ગદર્શિકા', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'ભૂસ્ખલન સુરક્ષા',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'ભૂસ્ખલન પહેલાં:',
        before: [
          'પહાડી વિસ્તારોમાં ભૂસ્ખલન સંભવિત વિસ્તારો જાણો',
          'જમીનનું ધોવાણ રોકવા વૃક્ષો વાવો અને ડ્રેનેજ સાફ રાખો',
          'ભારે વરસાદમાં નીચાણવાળા વિસ્તારોમાંથી સલામત સ્થળે ખસી જાઓ',
        ],
        duringTitle: 'ભૂસ્ખલન દરમિયાન:',
        during: [
          'કાટમાળના પ્રવાહના માર્ગમાંથી તરત જ દૂર થઈ જાઓ',
          'વૃક્ષો તૂટવાના કે અસામાન્ય અવાજો સાંભળી સાવધ રહો',
        ],
        afterTitle: 'ભૂસ્ખલન પછી:',
        after: [
          'ઘટના સ્થળની નજીક જશો નહીં; ફરીથી ભૂસ્ખલન થઈ શકે છે',
          'બચાવ ટીમને મદદ કરો',
        ],
        officialResourcesTitle: 'સત્તાવાર સંસાધનો:',
        resources: [
          { name: 'જિયોલોજિકલ સર્વે ઓફ ઇન્ડિયા (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'વાવાઝોડું સુરક્ષા',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'વાવાઝોડા પહેલાં:',
        before: [
          'હવામાન વિભાગ (IMD) ની ચેતવણીઓનું પાલન કરો',
          'છતના પતરા અને છૂટી વસ્તુઓને સુરક્ષિત કરો',
          'માછીમારોએ દરિયામાં જવું નહીં',
        ],
        duringTitle: 'વાવાઝોડા દરમિયાન:',
        during: [
          'મજબૂત પાકા મકાનોમાં બારીઓથી દૂર રહો',
          'તોફાનના કેન્દ્ર દરમિયાન શાંતિ જણાય તો પણ બહાર નીકળશો નહીં',
        ],
        afterTitle: 'વાવાઝોડા પછી:',
        after: [
          'તૂટેલા વીજ વાયરો અને પડી ગયેલા ઝાડથી સાવધ રહો',
          'માત્ર ઉકાળેલું પાણી પીવો',
        ],
        officialResourcesTitle: 'સત્તાવાર સંસાધનો:',
        resources: [
          { name: 'ભારતીય હવામાન વિભાગ (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'આગ સુરક્ષા',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'આગ લાગતા પહેલાં:',
        before: [
          'અગ્નિશામક સાધનો કાર્યરત સ્થિતિમાં રાખો',
          'કટોકટીના બહાર નીકળવાના માર્ગો હંમેશા ખુલ્લા રાખો',
          'પરિવાર સાથે બહાર નીકળવાની યોજના બનાવો',
        ],
        duringTitle: 'આગ લાગવા દરમિયાન:',
        during: [
          'સામાન લેવા રોકાયા વિના તરત જ બહાર નીકળો',
          'ધૂમાડો હોય તો જમીન પર સરકીને બહાર નીકળો',
          'કપડામાં આગ લાગે તો: ઊભા રહો, પડો અને ગબડો (STOP, DROP, ROLL)',
          'તાત્કાલિક 101 પર કોલ કરી અગ્નિશામક દળને જાણ કરો',
        ],
        afterTitle: 'આગ પછી:',
        after: [
          'અધિકારીઓ સુરક્ષિત જાહેર કરે પછી જ મકાનમાં પ્રવેશો',
          'દાઝેલા ભાગ પર ઠંડુ પાણી નાખો અને તબીબી સારવાર લો',
        ],
        officialResourcesTitle: 'સત્તાવાર સંસાધનો:',
        resources: [
          { name: 'અગ્નિશામક સેવાઓ પોર્ટલ (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'વધારાના રાષ્ટ્રીય સંસાધનો',
    additionalResources: [
      { name: 'રાષ્ટ્રીય આપત્તિ વ્યવસ્થાપન સત્તામંડળ (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'રાષ્ટ્રીય આપત્તિ પ્રતિભાવ દળ (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'સેન્ટ્રલ વોટર કમિશન (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'ઇન્ડિયન નેશનલ સેન્ટર ફોર ઓશન ઇન્ફોર્મેશન સર્વિસીસ (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  bn: {
    title: 'দুর্যোগ প্রস্তুতি ও সুরক্ষা নির্দেশিকা',
    subtitle: 'ভারতীয় সরকারি দুর্যোগ ব্যবস্থাপনা সংস্থার আনুষ্ঠানিক নির্দেশিকা',
    emergencyContactsTitle: 'জরুরি যোগাযোগ নম্বর',
    contacts: [
      { name: 'NDRF হেল্পলাইন', number: '011-24363260', description: 'জাতীয় দুর্যোগ মোকাবিলা বাহিনী' },
      { name: 'পুলিশ নিয়ন্ত্রণ কক্ষ', number: '100 / 112', description: 'জরুরি পুলিশ সহায়তা' },
      { name: 'দমকল বাহিনী', number: '101', description: 'দমকল ও উদ্ধার পরিষেবা' },
      { name: 'অ্যাম্বুলেন্স', number: '102 / 108', description: 'জরুরি চিকিৎসা সেবা' },
      { name: 'দুর্যোগ হেল্পলাইন', number: '1070 / 1078', description: 'জাতীয় দুর্যোগ হেল্পলাইন' },
      { name: 'মহিলা হেল্পলাইন', number: '1091', description: 'নারী সুরক্ষা হেল্পলাইন' },
    ],
    categories: [
      {
        disaster: 'বন্যা সুরক্ষা',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'বন্যার পূর্বে:',
        before: [
          'আপনার অঞ্চলের বন্যার ঝুঁকি এবং নিরাপদ আশ্রয়স্থল জানুন',
          'জরুরি নথিপত্র জলরোধী ব্যাগে সুরক্ষিত রাখুন',
          'পানীয় জল, শুকনো খাবার এবং প্রাথমিক চিকিৎসার কিট উঁচুতে রাখুন',
        ],
        duringTitle: 'বন্যার সময়:',
        during: [
          'অবিলম্বে উঁচু স্থান বা ত্রাণ শিবিরে আশ্রয় নিন',
          'বন্যার জলের মধ্যে দিয়ে হাঁটা বা গাড়ি চালানো পরিহার করুন',
          'বৈদ্যুতিক খুঁটি ও তার থেকে দূরে থাকুন',
        ],
        afterTitle: 'বন্যার পরে:',
        after: [
          'প্রশাসন নিরাপদ ঘোষণা করলেই ঘরে ফিরুন',
          'কেবলমাত্র ফুটানো বা বিশুদ্ধ জল পান করুন',
          'ছেঁড়া বিদ্যুতের তার স্পর্শ করবেন না',
        ],
        officialResourcesTitle: 'অফিসিয়াল তথ্যসূত্র:',
        resources: [
          { name: 'জাতীয় দুর্যোগ ব্যবস্থাপনা কর্তৃপক্ষ (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'ভূমিকম্প সুরক্ষা',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'ভূমিকম্পের পূর্বে:',
        before: [
          'ভারী আলমারি ও আসবাবপত্র দেওয়ালের সাথে শক্ত করে বাঁধুন',
          'শক্ত টেবিলের নিচে নিরাপদ জায়গা চিহ্নিত করুন',
          'জরুরি সরবরাহ কিট প্রস্তুত রাখুন',
        ],
        duringTitle: 'ভূমিকম্পের সময়:',
        during: [
          'মাটিতে বসুন, মাথা ঢাকুন এবং শক্ত করে ধরে রাখুন (DROP, COVER, HOLD ON)',
          'জানালা এবং কাচের জিনিসপত্র থেকে দূরে থাকুন',
          'লিফট ব্যবহার করবেন না; সিঁড়ি ব্যবহার করুন',
        ],
        afterTitle: 'ভূমিকম্পের পরে:',
        after: [
          'আহতদের প্রাথমিক চিকিৎসা দিন',
          'গ্যাস লিক পরীক্ষা করুন; আগুন জ্বালাবেন না',
          'পরবর্তী কম্পনের (আফটারশক) আশঙ্কায় সতর্ক থাকুন',
        ],
        officialResourcesTitle: 'অফিসিয়াল তথ্যসূত্র:',
        resources: [
          { name: 'NDMA ভূমিকম্প নির্দেশিকা', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'ভূমিধস সুরক্ষা',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'ভূমিধসের পূর্বে:',
        before: [
          'পাহাড়ি এলাকার ভূমিধস প্রবণ অঞ্চল সম্পর্কে সচেতন থাকুন',
          'মাটির ক্ষয় রোধে গাছ লাগান এবং নিকাশী ব্যবস্থা পরিষ্কার রাখুন',
          'ভারী বৃষ্টির সময় উপত্যকা অঞ্চল থেকে নিরাপদ স্থানে চলে যান',
        ],
        duringTitle: 'ভূমিধসের সময়:',
        during: [
          'ধস নামার পথ থেকে দ্রুত নিরাপদ স্থানে সরে যান',
          'গাছ ভাঙার বা অস্বাভাবিক শব্দ শুনে সতর্ক হন',
        ],
        afterTitle: 'ভূমিধসের পরে:',
        after: [
          'ধস কবলিত এলাকায় যাবেন না; পুনরায় ধসের আশঙ্কা থাকে',
          'উদ্ধারকারী দলকে সহায়তা করুন',
        ],
        officialResourcesTitle: 'অফিসিয়াল তথ্যসূত্র:',
        resources: [
          { name: 'জিওলজিক্যাল সার্ভে অফ ইন্ডিয়া (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'ঘূর্ণিঝড় সুরক্ষা',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'ঘূর্ণিঝড়ের পূর্বে:',
        before: [
          'আবহাওয়া দফতরের (IMD) সতর্কবার্তা নিয়মিত শুনুন',
          'ঘরের ছাদ এবং আলগা জিনিসপত্র মজবুত করুন',
          'মৎস্যজীবীরা সমুদ্রে যাবেন না',
        ],
        duringTitle: 'ঘূর্ণিঝড়ের সময়:',
        during: [
          'শক্ত কংক্রিটের বাড়িতে থাকুন, জানালা থেকে দূরে থাকুন',
          'ঝড়ের চোখ অতিক্রম করার সময় আপাত শান্ত আবহাওয়ায় বাইরে বের হবেন না',
        ],
        afterTitle: 'ঘূর্ণিঝড়ের পরে:',
        after: [
          'ছেঁড়া বিদ্যুতের তার এবং ভেঙে পড়া গাছ থেকে দূরে থাকুন',
          'ফুটানো জল পান করুন',
        ],
        officialResourcesTitle: 'অফিসিয়াল তথ্যসূত্র:',
        resources: [
          { name: 'ভারত আবহাওয়া বিভাগ (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'অগ্নিকাণ্ড সুরক্ষা',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'অগ্নিকাণ্ডের পূর্বে:',
        before: [
          'অগ্নি নির্বাপক যন্ত্র সচল অবস্থায় রাখুন',
          'জরুরি নির্গমন পথ সর্বদা পরিষ্কার রাখুন',
          'পরিবারের সাথে নির্গমন মহড়া অভ্যাস করুন',
        ],
        duringTitle: 'অগ্নিকাণ্ডের সময়:',
        during: [
          'জিনিসপত্র সংগ্রহের চেষ্টা না করে অবিলম্বে বের হয়ে আসুন',
          'ধোঁয়া থাকলে মেঝের উপর হামাগুড়ি দিয়ে বের হন',
          'পোশাকে আগুন লাগলে: থামুন, মাটিতে শুয়ে পড়ুন এবং গড়াগড়ি দিন (STOP, DROP, ROLL)',
          'দেরি না করে ১০১ নম্বরে দমকলে ফোন করুন',
        ],
        afterTitle: 'অগ্নিকাণ্ডের পরে:',
        after: [
          'দমকল বাহিনীর অনুমতি ছাড়া ক্ষতিগ্রস্ত ভবনে প্রবেশ করবেন না',
          'পোড়া স্থানে ঠান্ডা জল ঢালুন এবং চিকিৎসকের পরামর্শ নিন',
        ],
        officialResourcesTitle: 'অফিসিয়াল তথ্যসূত্র:',
        resources: [
          { name: 'অগ্নি নির্বাপণ পরিষেবা পোর্টাল', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'অন্যান্য জাতীয় সম্পদ',
    additionalResources: [
      { name: 'জাতীয় দুর্যোগ ব্যবস্থাপনা কর্তৃপক্ষ (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'জাতীয় দুর্যোগ মোকাবিলা বাহিনী (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'কেন্দ্রীয় জল কমিশন (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'ইন্ডিয়ান ন্যাশনাল সেন্টার ফর ওশান ইনফরমেশন সার্ভিসেস (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
  as: {
    title: 'দুৰ্যোগ প্ৰস্তুতি আৰু সুৰক্ষা নিৰ্দেশনাৱলী',
    subtitle: 'ভাৰতীয় চৰকাৰী দুৰ্যোগ ব্যৱস্থাপনা সংস্থাৰ আনুষ্ঠানিক নিৰ্দেশনা',
    emergencyContactsTitle: 'জৰুৰীকালীন যোগাযোগ নম্বৰ',
    contacts: [
      { name: 'এনডিআৰএফ হেল্পলাইন', number: '011-24363260', description: 'ৰাষ্ট্ৰীয় দুৰ্যোগ সঁহাৰি বাহিনী' },
      { name: 'আৰক্ষী নিয়ন্ত্ৰণ কক্ষ', number: '100 / 112', description: 'জৰুৰীকালীন আৰক্ষী সাহায্য' },
      { name: 'অগ্নি নিৰ্বাপক বাহিনী', number: '101', description: 'অগ্নি নিৰ্বাপণ আৰু উদ্ধাৰ কাৰ্য' },
      { name: 'এম্বুলেন্স সেৱা', number: '102 / 108', description: 'চিকিৎসা জৰুৰীকালীন সেৱা' },
      { name: 'দুৰ্যোগ হেল্পলাইন', number: '1070 / 1078', description: 'দুৰ্যোগ সাহায্য কক্ষ' },
      { name: 'মহিলা হেল্পলাইন', number: '1091', description: 'মহিলা সুৰক্ষা সাহায্য' },
    ],
    categories: [
      {
        disaster: 'বানপানী সুৰক্ষা',
        typeKey: 'flood',
        severity: 'Critical',
        beforeTitle: 'দুৰ্যোগৰ পূৰ্বে:',
        before: [
          'আপোনাৰ অঞ্চলৰ বানপানীৰ বিপদাশংকা আৰু নিৰাপদ আশ্ৰয়স্থল জানক',
          'প্ৰয়োজনীয় নথিপত্ৰ জলৰোধী মোনাত সুৰক্ষিত ৰাখক',
          'খোৱাপানী, শুকান খাদ্য আৰু প্ৰাথমিক চিকিৎসা কিট ওখ স্থানত মজুত কৰক',
        ],
        duringTitle: 'দুৰ্যোগৰ সময়ত:',
        during: [
          'ততালিকে ওখ স্থান বা সাহায্য শিবিৰলৈ যাওক',
          'পানীৰ সোঁতৰ মাজেৰে খোজ কঢ়া বা বাহন চলোৱা পৰিহাৰ কৰক',
          'বিদ্যুতৰ খুঁটা আৰু তাঁৰৰ পৰা আঁতৰি থাকক',
        ],
        afterTitle: 'দুৰ্যোগৰ পাছত:',
        after: [
          'প্ৰশাসনে সুৰক্ষিত বুলি ঘোষণা কৰিলেহে ঘৰলৈ উভতিব',
          'উতলা বা বিশুদ্ধ পানীহে খাব',
          'ছিঙি পৰা বিজুলীৰ তাঁৰ স্পৰ্শ নকৰিব',
        ],
        officialResourcesTitle: 'অফিচিয়েল তথ্যসূত্ৰ:',
        resources: [
          { name: 'ৰাষ্ট্ৰীয় দুৰ্যোগ ব্যৱস্থাপনা প্ৰাধিকৰণ (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
      {
        disaster: 'ভূমিকম্প সুৰক্ষা',
        typeKey: 'earthquake',
        severity: 'High',
        beforeTitle: 'দুৰ্যোগৰ পূৰ্বে:',
        before: [
          'গধুৰ আলমাৰী আৰু আচবাব বেৰৰ সৈতে মজবুতকৈ বান্ধক',
          'টান মেজৰ তলত নিৰাপদ স্থান চিনাক্ত কৰক',
          'জৰুৰীকালীন সঁজুলিৰ কিট সাজু কৰি ৰাখক',
        ],
        duringTitle: 'দুৰ্যোগৰ সময়ত:',
        during: [
          'মাটিত বহক, মূৰ ঢাকি ৰাখক আৰু টানকৈ ধৰক (DROP, COVER, HOLD ON)',
          'খিৰিকী আৰু কাচৰ বস্তুৰ পৰা আঁতৰত থাকক',
          'লিফ্ট ব্যৱহাৰ নকৰিব; জখলাহে ব্যৱহাৰ কৰক',
        ],
        afterTitle: 'দুৰ্যোগৰ পাছত:',
        after: [
          'আহতসকলক প্ৰাথমিক চিকিৎসা দিয়ক',
          'গেছ লিক হৈছে নেকি পৰীক্ষা কৰক; জুইশলা নজ্বলাব',
          'পুনৰ কম্পনৰ (আফটাৰশ্বক) আশংকাত সজাগ থাকক',
        ],
        officialResourcesTitle: 'অফিচিয়েল তথ্যসূত্ৰ:',
        resources: [
          { name: 'NDMA ভূমিকম্প নিৰ্দেশনাৱলী', url: 'https://ndma.gov.in/Natural-Hazards/Earthquakes' },
        ],
      },
      {
        disaster: 'ভূমিস্খলন সুৰক্ষা',
        typeKey: 'landslide',
        severity: 'Critical',
        beforeTitle: 'দুৰ্যোগৰ পূৰ্বে:',
        before: [
          'পাহাৰীয়া অঞ্চলৰ ভূমিস্খলন প্ৰৱণ এলেকাসমূহ জানক',
          'মাটিৰ খহনীয়া ৰোধ কৰিবলৈ গছ ৰোপণ কৰক',
          'প্ৰচণ্ড বৰষুণৰ সময়ত নদী উপত্যকাৰ পৰা নিৰাপদ ঠাইলৈ যাওক',
        ],
        duringTitle: 'দুৰ্যোগৰ সময়ত:',
        during: [
          'স্খলন ঘটা পথৰ পৰা তৎক্ষণাত আঁতৰি যাওক',
          'গছ ভঙাৰ বা অস্বাভাৱিক শব্দ শুনিলে সাৱধান হওক',
        ],
        afterTitle: 'দুৰ্যোগৰ পাছত:',
        after: [
          'স্খলন হোৱা স্থানলৈ নাযাব; পুনৰ খহনীয়া হ’ব পাৰে',
          'উদ্ধাৰকাৰী দলক সাহায্য কৰক',
        ],
        officialResourcesTitle: 'অফিচিয়েল তথ্যসূত্ৰ:',
        resources: [
          { name: 'ভাৰতীয় ভূতাত্ত্বিক জৰীপ (GSI)', url: 'https://www.gsi.gov.in/' },
        ],
      },
      {
        disaster: 'ঘূর্ণিবতাহ সুৰক্ষা',
        typeKey: 'cyclone',
        severity: 'High',
        beforeTitle: 'দুৰ্যোগৰ পূৰ্বে:',
        before: [
          'বতৰ বিজ্ঞান বিভাগৰ (IMD) সতৰ্কবাণীসমূহ নিয়মিত শুনক',
          'ঘৰৰ চাল আৰু খোলা বস্তুসমূহ মজবুতকৈ বান্ধক',
          'মৎসজীৱীসকলে নদীত বা সাগৰত নাৱেৰে যোৱা নিষিদ্ধ',
        ],
        duringTitle: 'দুৰ্যোগৰ সময়ত:',
        during: [
          'পকী ঘৰৰ ভিতৰত খিৰিকীৰ পৰা আঁতৰত থাকক',
          'বতাহ সাময়িকভাৱে কমিলেও বাহিৰলৈ ওলাই নাযাব',
        ],
        afterTitle: 'দুৰ্যোগৰ পাছত:',
        after: [
          'ছিঙি পৰা বিজুলীৰ তাঁৰ আৰু উভালি পৰা গছৰ পৰা সাৱধান থাকক',
          'উতলা পানীহে ব্যৱহাৰ কৰক',
        ],
        officialResourcesTitle: 'অফিচিয়েল তথ্যসূত্ৰ:',
        resources: [
          { name: 'ভাৰত বতৰ বিজ্ঞান বিভাগ (IMD)', url: 'https://mausam.imd.gov.in/' },
        ],
      },
      {
        disaster: 'অগ্নি নিৰ্বাপণ সুৰক্ষা',
        typeKey: 'fire',
        severity: 'Medium',
        beforeTitle: 'দুৰ্যোগৰ পূৰ্বে:',
        before: [
          'অগ্নি নিৰ্বাপক সঁজুলি সক্ৰিয় অৱস্থাত ৰাখক',
          'জৰুৰীকালীন ওলোৱা পথ সদায় মুকলি কৰি ৰাখক',
          'পৰিয়ালৰ সৈতে বাহিৰলৈ ওলোৱাৰ অভ্যাস কৰক',
        ],
        duringTitle: 'দুৰ্যোগৰ সময়ত:',
        during: [
          'সামগ্ৰী বুটলিবলৈ ৰৈ নাথাকি তৎক্ষণাত ওলাই আহক',
          'ধোঁৱা থাকিলে মজিয়াত বগাই ওলাই যাওক',
          'কাপোৰত জুই লাগিলে: ৰওক, মাটিত শুই দিয়ক আৰু বাগৰক (STOP, DROP, ROLL)',
          'পলম নকৰি ১০১ নম্বৰত অগ্নিনিৰ্বাপক বাহিনীক খবৰ দিয়ক',
        ],
        afterTitle: 'দুৰ্যোগৰ পাছত:',
        after: [
          'অগ্নি নিৰ্বাপক বিষয়াৰ অনুমতি অবিহনে ঘৰত প্ৰৱেশ নকৰিব',
          'জুইত পোৰা অংশত ঠাণ্ডা পানী দিয়ক আৰু শীঘ্ৰে চিকিৎসা লওক',
        ],
        officialResourcesTitle: 'অফিচিয়েল তথ্যসূত্ৰ:',
        resources: [
          { name: 'অগ্নি নিৰ্বাপণ সেৱা পৰ্টেল (NDMA)', url: 'https://ndma.gov.in/' },
        ],
      },
    ],
    additionalResourcesTitle: 'অন্যান্য ৰাষ্ট্ৰীয় পৰ্টেলসমূহ',
    additionalResources: [
      { name: 'ৰাষ্ট্ৰীয় দুৰ্যোগ ব্যৱস্থাপনা প্ৰাধিকৰণ (NDMA)', url: 'https://ndma.gov.in/' },
      { name: 'ৰাষ্ট্ৰীয় দুৰ্যোগ সঁহাৰি বাহিনী (NDRF)', url: 'https://ndrf.gov.in/' },
      { name: 'কেন্দ্ৰীয় জল আয়োগ (CWC)', url: 'http://www.cwc.gov.in/' },
      { name: 'ভাৰতীয় ৰাষ্ট্ৰীয় মহাসাগৰ তথ্য সেৱা কেন্দ্ৰ (INCOIS)', url: 'https://incois.gov.in/' },
    ],
  },
};


// Weather Translations Dictionary
export interface WeatherDictionary {
  searchPlaceholder: string;
  noCitiesFound: string;
  showingWeatherFor: string;
  climateIntelligence: string;
  feelsLike: string;
  humidity: string;
  windVelocity: string;
  precipitation: string;
  visibility: string;
  pressure: string;
  sunrise: string;
  sunset: string;
  windDir: string;
  uvIndex: string;
  airQuality: string;
  comfortLevel: string;
  nearTermForecast: string;
  weeklyOutlook: string;
  criticalAlerts: string;
  starts: string;
  ends: string;
  activeWarnings: string;
  weatherUnavailable: string;
  checkLocationSettings: string;
  uvLevels: { low: string; moderate: string; high: string; veryHigh: string; extreme: string };
  comfortLevels: { veryHot: string; hot: string; perfect: string; cool: string; cold: string };
  conditions: Record<string, string>;
}

export const VERNACULAR_WEATHER: Record<SupportedLanguageCode, WeatherDictionary> = {
  ml: {
    searchPlaceholder: 'കാലാവസ്ഥ അറിയാൻ നഗരത്തിന്റെ പേര് തിരയുക...',
    noCitiesFound: 'നഗരം കണ്ടെത്താനായില്ല',
    showingWeatherFor: 'നിലവിലെ സ്ഥലം:',
    climateIntelligence: 'കാലാവസ്ഥാ നിരീക്ഷണം',
    feelsLike: 'അനുഭവപ്പെടുന്നത്',
    humidity: 'ആർദ്രത (ഈർപ്പം)',
    windVelocity: 'കാറ്റിന്റെ വേഗത',
    precipitation: 'മഴയുടെ അളവ്',
    visibility: 'കാഴ്ചാപരിധി',
    pressure: 'അന്തരീക്ഷ മർദ്ദം',
    sunrise: 'സൂര്യോദയം',
    sunset: 'സൂര്യാസ്തമയം',
    windDir: 'കാറ്റിന്റെ ദിശ',
    uvIndex: 'അൾട്രാവയലറ്റ് ഇൻഡക്സ്',
    airQuality: 'വായു ഗുണനിലവാരം',
    comfortLevel: 'ആശ്വാസ നിലവാരം',
    nearTermForecast: 'അടുത്ത 24 മണിക്കൂർ പ്രവചനം',
    weeklyOutlook: 'ഈ ആഴ്ചയിലെ കാലാവസ്ഥ',
    criticalAlerts: 'തീവ്ര കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ',
    starts: 'ആരംഭം',
    ends: 'അവസാനം',
    activeWarnings: 'സജീവ മുന്നറിയിപ്പുകൾ',
    weatherUnavailable: 'കാലാവസ്ഥാ വിവരങ്ങൾ ലഭ്യമല്ല',
    checkLocationSettings: 'ദയവായി ലൊക്കേഷൻ ക്രമീകരണങ്ങൾ പരിശോധിക്കുക.',
    uvLevels: { low: 'കുറവ്', moderate: 'മിതമായത്', high: 'കൂടുതൽ', veryHigh: 'വളരെ കൂടുതൽ', extreme: 'അതിതീവ്രം' },
    comfortLevels: { veryHot: 'കഠിനമായ ചൂട്', hot: 'ചൂട്', perfect: 'സുഖകരം', cool: 'തണുപ്പ്', cold: 'കഠിനമായ തണുപ്പ്' },
    conditions: {
      clear: 'തെളിഞ്ഞ ആകാശം',
      clouds: 'മേഘാവൃതം',
      rain: 'മഴ',
      drizzle: 'ചാറ്റൽമഴ',
      thunderstorm: 'ഇടിമിന്നലോടുകൂടിയ മഴ',
      snow: 'മഞ്ഞുവീഴ്ച',
      mist: 'മൂടൽമഞ്ഞ്',
      fog: 'കനത്ത മൂടൽമഞ്ഞ്',
      haze: 'ധൂമ്രപടലം',
    },
  },
  hi: {
    searchPlaceholder: 'मौसम देखने के लिए शहर खोजें...',
    noCitiesFound: 'कोई शहर नहीं मिला',
    showingWeatherFor: 'मौसम स्थान:',
    climateIntelligence: 'जलवायु बुद्धिमत्ता',
    feelsLike: 'महसूस हो रहा है',
    humidity: 'आर्द्रता',
    windVelocity: 'हवा की गति',
    precipitation: 'वर्षा की मात्रा',
    visibility: 'दृश्यता',
    pressure: 'वायुमंडलीय दबाव',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    windDir: 'हवा की दिशा',
    uvIndex: 'यूवी इंडेक्स',
    airQuality: 'वायु गुणवत्ता',
    comfortLevel: 'आराम स्तर',
    nearTermForecast: 'अगले 24 घंटे का पूर्वानुमान',
    weeklyOutlook: 'साप्ताहिक मौसम दृष्टिकोण',
    criticalAlerts: 'गंभीर मौसम चेतावनियां',
    starts: 'प्रारंभ',
    ends: 'समाप्त',
    activeWarnings: 'सक्रिय चेतावनियां',
    weatherUnavailable: 'मौसम डेटा अनुपलब्ध',
    checkLocationSettings: 'कृपया अपनी स्थान सेटिंग्स जांचें।',
    uvLevels: { low: 'कम', moderate: 'मध्यम', high: 'अधिक', veryHigh: 'बहुत अधिक', extreme: 'अत्यधिक' },
    comfortLevels: { veryHot: 'बहुत गर्म', hot: 'गर्म', perfect: 'उत्तम', cool: 'शीतल', cold: 'ठंडा' },
    conditions: {
      clear: 'साफ आसमान',
      clouds: 'बादल छाए हैं',
      rain: 'बारिश',
      drizzle: 'बूंदाबांदी',
      thunderstorm: 'गरज के साथ बारिश',
      snow: 'बर्फबारी',
      mist: 'धुंध',
      fog: 'कोहरा',
      haze: 'धुंधलापन',
    },
  },
  en: {
    searchPlaceholder: 'Search city to view weather...',
    noCitiesFound: 'No cities found',
    showingWeatherFor: 'Showing weather for:',
    climateIntelligence: 'Climate Intelligence',
    feelsLike: 'Feels like',
    humidity: 'Humidity',
    windVelocity: 'Wind Velocity',
    precipitation: 'Precipitation',
    visibility: 'Visibility',
    pressure: 'Pressure',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    windDir: 'Wind Dir.',
    uvIndex: 'UV Index',
    airQuality: 'Air Quality',
    comfortLevel: 'Comfort Level',
    nearTermForecast: 'Near-Term Forecast',
    weeklyOutlook: 'Weekly Outlook',
    criticalAlerts: 'Critical Alerts',
    starts: 'Starts',
    ends: 'Ends',
    activeWarnings: 'Active Warnings',
    weatherUnavailable: 'Weather Data Unavailable',
    checkLocationSettings: 'Unable to fetch weather information. Please check your location settings.',
    uvLevels: { low: 'Low', moderate: 'Moderate', high: 'High', veryHigh: 'Very High', extreme: 'Extreme' },
    comfortLevels: { veryHot: 'Very Hot', hot: 'Hot', perfect: 'Perfect', cool: 'Cool', cold: 'Cold' },
    conditions: {
      clear: 'Clear Sky',
      clouds: 'Cloudy',
      rain: 'Rain',
      drizzle: 'Drizzle',
      thunderstorm: 'Thunderstorm',
      snow: 'Snow',
      mist: 'Mist',
      fog: 'Fog',
      haze: 'Haze',
    },
  },
  gu: {} as any,
  mr: {} as any,
  ta: {} as any,
  te: {} as any,
  as: {} as any,
  bn: {} as any,
};

VERNACULAR_WEATHER.ta = {
  searchPlaceholder: 'வானிலை அறிய நகரத்தைத் தேடுங்கள்...',
  noCitiesFound: 'நகரம் கிடைக்கவில்லை',
  showingWeatherFor: 'தற்போதைய இடம்:',
  climateIntelligence: 'வானிலை நுண்ணறிவு',
  feelsLike: 'உணரப்படுவது',
  humidity: 'ஈரப்பதம்',
  windVelocity: 'காற்றின் வேகம்',
  precipitation: 'மழைப்பொழிவு',
  visibility: 'பார்வைத்திறன்',
  pressure: 'வளிமண்டல அழுத்தம்',
  sunrise: 'சூரிய உதயம்',
  sunset: 'சூரிய அஸ்தமனம்',
  windDir: 'காற்றின் திசை',
  uvIndex: 'யுவி குறியீடு',
  airQuality: 'காற்று தரம்',
  comfortLevel: 'வசதி நிலை',
  nearTermForecast: 'அடுத்த 24 மணிநேர முன்னறிவிப்பு',
  weeklyOutlook: 'வாராந்திர முன்னறிவிப்பு',
  criticalAlerts: 'தீவிர வானிலை எச்சரிக்கைகள்',
  starts: 'தொடக்கம்',
  ends: 'முடிவு',
  activeWarnings: 'செயலில் உள்ள எச்சரிக்கைகள்',
  weatherUnavailable: 'வானிலை தரவு கிடைக்கவில்லை',
  checkLocationSettings: 'இருப்பிட அமைப்புகளை சரிபார்க்கவும்.',
  uvLevels: { low: 'குறைவு', moderate: 'மிதமானது', high: 'அதிகம்', veryHigh: 'மிக அதிகம்', extreme: 'தீவிரம்' },
  comfortLevels: { veryHot: 'அதிக வெப்பம்', hot: 'வெப்பம்', perfect: 'இதமானது', cool: 'குளிர்ச்சி', cold: 'அதிக குளிர்' },
  conditions: {
    clear: 'தெளிவான வானம்',
    clouds: 'மேகமூட்டம்',
    rain: 'மழை',
    drizzle: 'தூறல்',
    thunderstorm: 'இடியுடன் கூடிய மழை',
    snow: 'பனிப்பொழிவு',
    mist: 'மூடுபனி',
    fog: 'கடும் மூடுபனி',
    haze: 'புகைமூட்டம்',
  },
};

VERNACULAR_WEATHER.te = {
  searchPlaceholder: 'వాతావరణం చూడటానికి నగరాన్ని వెతకండి...',
  noCitiesFound: 'నగరం కనుగొనబడలేదు',
  showingWeatherFor: 'ప్రస్తుత ప్రాంతం:',
  climateIntelligence: 'వాతావరణ పరిశీలన',
  feelsLike: 'అనిపిస్తుంది',
  humidity: 'తేమ',
  windVelocity: 'గాలి వేగం',
  precipitation: 'వర్షపాతం',
  visibility: 'దృశ్యమానత',
  pressure: 'పీడనం',
  sunrise: 'సూర్యోదయం',
  sunset: 'సూర్యాస్తమయం',
  windDir: 'గాలి దిశ',
  uvIndex: 'యువి సూచిక',
  airQuality: 'గాలి నాణ్యత',
  comfortLevel: 'సౌకర్య స్థాయి',
  nearTermForecast: 'తదుపరి 24 గంటల అంచనా',
  weeklyOutlook: 'వారపు సూచన',
  criticalAlerts: 'తీవ్రమైన వాతావరణ హెచ్చరికలు',
  starts: 'ప్రారంభం',
  ends: 'ముగింపు',
  activeWarnings: 'చురుకైన హెచ్చరికలు',
  weatherUnavailable: 'వాతావరణ సమాచారం అందుబాటులో లేదు',
  checkLocationSettings: 'దయచేసి లొకేషన్ సెట్టింగ్‌లను తనిఖీ చేయండి.',
  uvLevels: { low: 'తక్కువ', moderate: 'మధ్యస్థం', high: 'ఎక్కువ', veryHigh: 'చాలా ఎక్కువ', extreme: 'తీవ్రం' },
  comfortLevels: { veryHot: 'చాలా వేడి', hot: 'వేడి', perfect: 'అనుకూలం', cool: 'చల్లదనం', cold: 'చలి' },
  conditions: {
    clear: 'నిర్మలమైన ఆకాశం',
    clouds: 'మేఘావృతం',
    rain: 'వర్షం',
    drizzle: 'చినుకులు',
    thunderstorm: 'ఉరుములతో కూడిన వర్షం',
    snow: 'మంచు కురవడం',
    mist: 'పొగమంచు',
    fog: 'దట్టమైన మంచు',
    haze: 'మసక',
  },
};

VERNACULAR_WEATHER.mr = {
  searchPlaceholder: 'हवामान पाहण्यासाठी शहर शोधा...',
  noCitiesFound: 'शहर सापडले नाही',
  showingWeatherFor: 'सध्याचे ठिकाण:',
  climateIntelligence: 'हवामान विश्लेषण',
  feelsLike: 'जाणवणारे तापमान',
  humidity: 'आर्द्रता',
  windVelocity: 'वाऱ्याचा वेग',
  precipitation: 'पावसाचे प्रमाण',
  visibility: 'दृश्यमानता',
  pressure: 'हवेचा दाब',
  sunrise: 'सूर्योदय',
  sunset: 'सूर्यास्त',
  windDir: 'वाऱ्याची दिशा',
  uvIndex: 'अतिनील निर्देशांक',
  airQuality: 'हवेची गुणवत्ता',
  comfortLevel: 'आराम पातळी',
  nearTermForecast: 'पुढील २४ तासांचा अंदाज',
  weeklyOutlook: 'साप्ताहिक हवामान अंदाज',
  criticalAlerts: 'गंभीर हवामान इशारे',
  starts: 'सुरुवात',
  ends: 'समाप्ती',
  activeWarnings: 'सक्रिय इशारे',
  weatherUnavailable: 'हवामान माहिती अनुपलब्ध',
  checkLocationSettings: 'कृपया स्थान सेटिंग्ज तपासा.',
  uvLevels: { low: 'कमी', moderate: 'मध्यम', high: 'जास्त', veryHigh: 'खूप जास्त', extreme: 'अतिशय जास्त' },
  comfortLevels: { veryHot: 'खूप उष्ण', hot: 'उष्ण', perfect: 'उत्तम', cool: 'थंडगार', cold: 'कडाक्याची थंडी' },
  conditions: {
    clear: 'निरभ्र आकाश',
    clouds: 'ढगाळ वातावरण',
    rain: 'पाऊस',
    drizzle: 'रिमझिम पाऊस',
    thunderstorm: 'वादळी पाऊस',
    snow: 'बर्फवृष्टी',
    mist: 'धुके',
    fog: 'दाट धुके',
    haze: 'धुरकट वातावरण',
  },
};

VERNACULAR_WEATHER.gu = {
  searchPlaceholder: 'હવામાન જોવા માટે શહેર શોધો...',
  noCitiesFound: 'શહેર મળ્યું નથી',
  showingWeatherFor: 'હાલનું સ્થળ:',
  climateIntelligence: 'હવામાન વિશ્લેષણ',
  feelsLike: 'અનુભવાતું તાપમાન',
  humidity: 'ભેજ',
  windVelocity: 'પવનની ઝડપ',
  precipitation: 'વરસાદ',
  visibility: 'દૃશ્યતા',
  pressure: 'દબાણ',
  sunrise: 'સૂર્યોદય',
  sunset: 'સૂર્યાસ્ત',
  windDir: 'પવનની દિશા',
  uvIndex: 'યુવી ઇન્ડેક્સ',
  airQuality: 'હવાની ગુણવત્તા',
  comfortLevel: 'આરામ સ્તર',
  nearTermForecast: 'આગામી 24 કલાકની આગાહી',
  weeklyOutlook: 'સાપ્તાહિક દૃષ્ટિકોણ',
  criticalAlerts: 'ગંભીર હવામાન ચેતવણીઓ',
  starts: 'શરૂઆત',
  ends: 'અંત',
  activeWarnings: 'સક્રિય ચેતવણીઓ',
  weatherUnavailable: 'હવામાન માહિતી અનુપલબ્ધ',
  checkLocationSettings: 'કૃપા કરીને સ્થાન સેટિંગ્સ તપાસો.',
  uvLevels: { low: 'ઓછું', moderate: 'મધ્યમ', high: 'વધુ', veryHigh: 'ઘણું વધુ', extreme: 'અત્યંત' },
  comfortLevels: { veryHot: 'ખૂબ ગરમ', hot: 'ગરમ', perfect: 'ઉત્તમ', cool: 'ઠંડુ', cold: 'અતિશય ઠંડી' },
  conditions: {
    clear: 'સ્વચ્છ આકાશ',
    clouds: 'વાદળછાયું',
    rain: 'વરસાદ',
    drizzle: 'ઝરમર વરસાદ',
    thunderstorm: 'ગાજવીજ સાથે વરસાદ',
    snow: 'હિમવર્ષા',
    mist: 'ધુમ્મસ',
    fog: 'ગાઢ ધુમ્મસ',
    haze: 'ઝાકળ',
  },
};

VERNACULAR_WEATHER.bn = {
  searchPlaceholder: 'আবহাওয়া দেখতে শহরের নাম খুঁজুন...',
  noCitiesFound: 'কোনো শহর পাওয়া যায়নি',
  showingWeatherFor: 'বর্তমান অবস্থান:',
  climateIntelligence: 'আবহাওয়া পর্যবেক্ষণ',
  feelsLike: 'অনুভূত তাপমাত্রা',
  humidity: 'আর্দ্রতা',
  windVelocity: 'বাতাসের গতিবেগ',
  precipitation: 'বৃষ্টিপাত',
  visibility: 'দৃশ্যমানতা',
  pressure: 'বায়ুমণ্ডলীয় চাপ',
  sunrise: 'সূর্যোদয়',
  sunset: 'সূর্যাস্ত',
  windDir: 'বাতাসের দিক',
  uvIndex: 'ইউভি সূচক',
  airQuality: 'বায়ুর মান',
  comfortLevel: 'স্বাচ্ছন্দ্য স্তর',
  nearTermForecast: 'পরবর্তী ২৪ ঘণ্টার পূর্বাভাস',
  weeklyOutlook: 'সাপ্তাহিক আবহাওয়া',
  criticalAlerts: 'জরুরি আবহাওয়া সতর্কতা',
  starts: 'শুরু',
  ends: 'শেষ',
  activeWarnings: 'সক্রিয় সতর্কতা',
  weatherUnavailable: 'আবহাওয়ার তথ্য পাওয়া যায়নি',
  checkLocationSettings: 'অনুগ্রহ করে অবস্থান সেটিংস পরীক্ষা করুন।',
  uvLevels: { low: 'কম', moderate: 'মাঝারি', high: 'বেশি', veryHigh: 'খুব বেশি', extreme: 'চরম' },
  comfortLevels: { veryHot: 'অতিরিক্ত গরম', hot: 'গরম', perfect: 'মনোরম', cool: 'শীতল', cold: 'তীব্র শীত' },
  conditions: {
    clear: 'পরিষ্কার আকাশ',
    clouds: 'মেঘলা',
    rain: 'বৃষ্টি',
    drizzle: 'গুড়ি গুড়ি বৃষ্টি',
    thunderstorm: 'বজ্রবিদ্যুৎসহ বৃষ্টি',
    snow: 'তুষারপাত',
    mist: 'কুয়াশা',
    fog: 'ঘন কুয়াশা',
    haze: 'ধোঁয়াশা',
  },
};

VERNACULAR_WEATHER.as = {
  searchPlaceholder: 'বতৰ চাবলৈ চহৰৰ নাম সন্ধান কৰক...',
  noCitiesFound: 'কোনো চহৰ পোৱা নগ’ল',
  showingWeatherFor: 'বৰ্তমান স্থান:',
  climateIntelligence: 'বতৰ নিৰীক্ষণ',
  feelsLike: 'অনুভৱ হোৱা উষ্ণতা',
  humidity: 'আৰ্দ্ৰতা',
  windVelocity: 'বতাহৰ গতিবেগ',
  precipitation: 'বৰষুণৰ পৰিমাণ',
  visibility: 'দৃশ্যমানতা',
  pressure: 'বায়ুমণ্ডলীয় চাপ',
  sunrise: 'সূৰ্যোদয়',
  sunset: 'সূৰ্যাস্ত',
  windDir: 'বতাহৰ দিশ',
  uvIndex: 'ইউভি সূচক',
  airQuality: 'বায়ুৰ মান',
  comfortLevel: 'আৰামৰ স্তৰ',
  nearTermForecast: 'পৰৱৰ্তী ২৪ ঘণ্টাৰ বতৰৰ আগজাননী',
  weeklyOutlook: 'সাপ্তাহিক বতৰ',
  criticalAlerts: 'গুৰুতৰ বতৰৰ সতৰ্কবাণী',
  starts: 'আৰম্ভণি',
  ends: 'সমাপ্তি',
  activeWarnings: 'সক্ৰিয় সতৰ্কবাণী',
  weatherUnavailable: 'বতৰৰ তথ্য উপলব্ধ নহয়',
  checkLocationSettings: 'অনুগ্ৰহ কৰি স্থান ছেটিংছ পৰীক্ষা কৰক।',
  uvLevels: { low: 'কম', moderate: 'মধ্যমীয়া', high: 'বেছি', veryHigh: 'অতি বেছি', extreme: 'চৰম' },
  comfortLevels: { veryHot: 'অতিপাত গৰম', hot: 'গৰম', perfect: 'মনোৰম', cool: 'শীতল', cold: 'কঁকাল কঁপোৱা জাৰ' },
  conditions: {
    clear: 'পৰিষ্কাৰ আকাশ',
    clouds: 'ডাৱৰীয়া',
    rain: 'বৰষুণ',
    drizzle: 'টোপাটোপে বৰষুণ',
    thunderstorm: 'বজ্ৰপাতসহ বৰষুণ',
    snow: 'হিমপাত',
    mist: 'কুঁৱলী',
    fog: 'ঘন কুঁৱলী',
    haze: 'ধূঁৱলী-কুঁৱলী',
  },
};

// Volunteer Hub Dictionary
export interface VolunteerHubDictionary {
  pageTitle: string;
  pageSubtitle: string;
  listResourceBtn: string;
  tabResources: string;
  tabRescueML: string;
  formTitle: string;
  labelType: string;
  labelName: string;
  labelContact: string;
  labelLocation: string;
  labelDescription: string;
  btnCancel: string;
  btnPost: string;
  types: {
    vehicle: string;
    food: string;
    water: string;
    medical: string;
    other: string;
  };
  statuses: {
    available: string;
    inUse: string;
    needed: string;
  };
  filterAll: string;
  searchPlaceholder: string;
  noResourcesFound: string;
  signalAnalysisTitle: string;
  signalPlaceholder: string;
  btnAnalyzeSignal: string;
  loadingModel: string;
  analyzingText: string;
  mlResultsTitle: string;
  volunteerBadge: string;
  volunteerDialogTitle: string;
  volunteerDialogDesc: string;
  volunteerSkillsLabel: string;
  btnRegisterVolunteer: string;
}

export const VERNACULAR_VOLUNTEER: Record<SupportedLanguageCode, VolunteerHubDictionary> = {
  ml: {
    pageTitle: 'ദുരിതാശ്വാസ റിസോഴ്സ് ഹബ്',
    pageSubtitle: 'സന്നദ്ധ പ്രവർത്തക ഏകോപനവും ദുരിതാശ്വാസ സാമഗ്രികളും',
    listResourceBtn: 'സഹായ സാമഗ്രി രജിസ്റ്റർ ചെയ്യുക',
    tabResources: 'ലഭ്യമായ സാമഗ്രികൾ',
    tabRescueML: 'രക്ഷാപ്രവർത്തന സിഗ്നൽ എഐ',
    formTitle: 'പുതിയ സഹായ സാമഗ്രി ചേർക്കുക',
    labelType: 'ഇനം',
    labelName: 'പേര് / വിവരണം',
    labelContact: 'ഫോൺ നമ്പർ',
    labelLocation: 'സ്ഥലം / പ്രദേശം',
    labelDescription: 'വിശദാംശങ്ങൾ',
    btnCancel: 'റദ്ദാക്കുക',
    btnPost: 'രജിസ്റ്റർ ചെയ്യുക',
    types: {
      vehicle: 'വാഹനം / ബോട്ട്',
      food: 'ഭക്ഷണ സാമഗ്രികൾ',
      water: 'കുടിവെള്ളം',
      medical: 'വൈദ്യസഹായം',
      other: 'മറ്റ് അവശ്യവസ്തുക്കൾ',
    },
    statuses: {
      available: 'ലഭ്യമാണ്',
      inUse: 'ഉപയോഗത്തിലാണ്',
      needed: 'ആവശ്യമുണ്ട്',
    },
    filterAll: 'എല്ലാം',
    searchPlaceholder: 'സാമഗ്രികളും സ്ഥലങ്ങളും തിരയുക...',
    noResourcesFound: 'സഹായ സാമഗ്രികളൊന്നും കണ്ടെത്തിയില്ല.',
    signalAnalysisTitle: 'അടിയന്തര സന്ദേശ സിഗ്നൽ പരിശോധന (എഐ)',
    signalPlaceholder: 'സോഷ്യൽ മീഡിയയിൽ നിന്നോ സന്ദേശങ്ങളിൽ നിന്നോ ഉള്ള സഹായാഭ്യർത്ഥന ഇവിടെ നൽകുക...',
    btnAnalyzeSignal: 'സിഗ്നൽ പരിശോധിക്കുക',
    loadingModel: 'എഐ മോഡൽ തയ്യാറാകുന്നു...',
    analyzingText: 'പരിശോധിക്കുന്നു...',
    mlResultsTitle: 'സിഗ്നൽ വിശകലന ഫലം',
    volunteerBadge: 'സന്നദ്ധ പ്രവർത്തകൻ',
    volunteerDialogTitle: 'സന്നദ്ധ പ്രവർത്തകനായി രജിസ്റ്റർ ചെയ്യുക',
    volunteerDialogDesc: 'ദുരന്തമുഖത്ത് ജനങ്ങളെ സഹായിക്കാൻ സന്നദ്ധസേനയുടെ ഭാഗമാകൂ.',
    volunteerSkillsLabel: 'പ്രത്യേക കഴിവുകൾ (നീന്തൽ, പ്രഥമശുശ്രൂഷ, ഡ്രൈവിംഗ് മുതലായവ)',
    btnRegisterVolunteer: 'രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക',
  },
  hi: {
    pageTitle: 'सामुदायिक संसाधन केंद्र',
    pageSubtitle: 'स्वयंसेवक समन्वय और राहत सामग्री प्रबंधन',
    listResourceBtn: 'संसाधन सूची में जोड़ें',
    tabResources: 'उपलब्ध संसाधन',
    tabRescueML: 'बचाव संदेश विश्लेषण',
    formTitle: 'नई संसाधन प्रविष्टि',
    labelType: 'प्रकार',
    labelName: 'नाम / विवरण',
    labelContact: 'संपर्क नंबर',
    labelLocation: 'स्थान / क्षेत्र',
    labelDescription: 'विस्तृत जानकारी',
    btnCancel: 'रद्द करें',
    btnPost: 'सूचीबद्ध करें',
    types: {
      vehicle: 'वाहन / नौका',
      food: 'खाद्य सामग्री',
      water: 'पेयजल',
      medical: 'चिकित्सा सहायता',
      other: 'अन्य राहत सामग्री',
    },
    statuses: {
      available: 'उपलब्ध',
      inUse: 'उपयोग में',
      needed: 'आवश्यकता है',
    },
    filterAll: 'सभी',
    searchPlaceholder: 'संसाधन या स्थान खोजें...',
    noResourcesFound: 'कोई संसाधन नहीं मिला।',
    signalAnalysisTitle: 'आपातकालीन संदेश विश्लेषण (AI)',
    signalPlaceholder: 'आपातकालीन संदेश यहां पेस्ट करें...',
    btnAnalyzeSignal: 'संदेश का विश्लेषण करें',
    loadingModel: 'एआई मॉडल लोड हो रहा है...',
    analyzingText: 'विश्लेषण जारी है...',
    mlResultsTitle: 'एआई विश्लेषण परिणाम',
    volunteerBadge: 'सक्रिय स्वयंसेवक',
    volunteerDialogTitle: 'स्वयंसेवक के रूप में पंजीकरण करें',
    volunteerDialogDesc: 'संकट के समय राहत कार्यों में भाग लें।',
    volunteerSkillsLabel: 'विशेष कौशल (तैराकी, प्राथमिक चिकित्सा आदि)',
    btnRegisterVolunteer: 'पंजीकरण पूरा करें',
  },
  en: {
    pageTitle: 'Community Resource Hub',
    pageSubtitle: 'Coordination & Relief Material Management',
    listResourceBtn: 'List a Resource',
    tabResources: 'Resources',
    tabRescueML: 'Rescue Dispatch ML',
    formTitle: 'New Resource Listing',
    labelType: 'Type',
    labelName: 'Name / Title',
    labelContact: 'Contact Number',
    labelLocation: 'Location / Area',
    labelDescription: 'Description',
    btnCancel: 'Cancel',
    btnPost: 'Post Listing',
    types: {
      vehicle: 'Vehicle / Transport',
      food: 'Food Supplies',
      water: 'Drinking Water',
      medical: 'Medical Assistance',
      other: 'Other Relief Materials',
    },
    statuses: {
      available: 'Available',
      inUse: 'In Use',
      needed: 'Needed',
    },
    filterAll: 'All',
    searchPlaceholder: 'Search resources or locations...',
    noResourcesFound: 'No resources found.',
    signalAnalysisTitle: 'Emergency Report Signal Analysis',
    signalPlaceholder: 'Paste community emergency messages here for classification...',
    btnAnalyzeSignal: 'Analyze Signal',
    loadingModel: 'Loading Model...',
    analyzingText: 'Analyzing...',
    mlResultsTitle: 'ML Signal Decoding Results',
    volunteerBadge: 'Verified Volunteer',
    volunteerDialogTitle: 'Register as a Volunteer',
    volunteerDialogDesc: 'Join relief operations in high-priority zones.',
    volunteerSkillsLabel: 'Special Skills (Swimming, First Aid, Driving, etc.)',
    btnRegisterVolunteer: 'Complete Registration',
  },
  gu: {} as any,
  mr: {} as any,
  ta: {} as any,
  te: {} as any,
  as: {} as any,
  bn: {} as any,
};

VERNACULAR_VOLUNTEER.ta = {
  ...VERNACULAR_VOLUNTEER.hi,
  pageTitle: 'சமூக நிவாரண வள மையம்',
  pageSubtitle: 'தன்னார்வலர் ஒருங்கிணைப்பு மற்றும் நிவாரண பொருட்கள்',
  listResourceBtn: 'வளத்தை பட்டியலிடுங்கள்',
  tabResources: 'நிவாரண வளங்கள்',
  tabRescueML: 'மீட்பு சமிக்ஞை பகுப்பாய்வு',
  formTitle: 'புதிய வள பதிவு',
  btnCancel: 'ரத்துசெய்',
  btnPost: 'பதிவு செய்க',
  filterAll: 'அனைத்தும்',
  searchPlaceholder: 'வளங்கள் அல்லது இடங்களைத் தேடுங்கள்...',
  noResourcesFound: 'வளங்கள் எதுவும் கிடைக்கவில்லை.',
  types: {
    vehicle: 'வாகனம் / படகு',
    food: 'உணவு பொருட்கள்',
    water: 'குடிநீர்',
    medical: 'மருத்துவ உதவி',
    other: 'பிற பொருட்கள்',
  },
  statuses: {
    available: 'கிடைக்கிறது',
    inUse: 'பயன்பாட்டில் உள்ளது',
    needed: 'தேவைப்படுகிறது',
  },
};

VERNACULAR_VOLUNTEER.te = {
  ...VERNACULAR_VOLUNTEER.hi,
  pageTitle: 'కమ్యూనిటీ వనరుల కేంద్రం',
  pageSubtitle: 'వాలంటీర్ సమన్వయం మరియు సహాయ సామగ్రి',
  listResourceBtn: 'వనరును జాబితా చేయండి',
  tabResources: 'అందుబాటులో ఉన్న వనరులు',
  tabRescueML: 'రక్షణ సిగ్నల్ విశ్లేషణ',
  formTitle: 'కొత్త వనరుల నమోదు',
  btnCancel: 'రద్దు చేయి',
  btnPost: 'నమోదు చేయి',
  filterAll: 'అన్నీ',
  searchPlaceholder: 'వనరులు లేదా ప్రాంతాలను శోధించండి...',
  noResourcesFound: 'వనరులు కనుగొనబడలేదు.',
  types: {
    vehicle: 'వాహనం / పడవ',
    food: 'ఆహార సామాగ్రి',
    water: 'తాగునీరు',
    medical: 'వైద్య సహాయం',
    other: 'ఇతర వస్తువులు',
  },
  statuses: {
    available: 'అందుబాటులో ఉంది',
    inUse: 'ఉపయోగంలో ఉంది',
    needed: 'అవసరం',
  },
};

VERNACULAR_VOLUNTEER.mr = {
  ...VERNACULAR_VOLUNTEER.hi,
  pageTitle: 'सामुदायिक संसाधन केंद्र',
  pageSubtitle: 'स्वयंसेवक समन्वय आणि मदत साहित्य व्यवस्थापन',
  listResourceBtn: 'साहित्य नोंदवा',
  tabResources: 'उपलब्ध साहित्य',
  tabRescueML: 'बचाव संदेश विश्लेषण',
  formTitle: 'नवीन नोंदणी',
  btnCancel: 'रद्द करा',
  btnPost: 'नोंदवा',
  filterAll: 'सर्व',
  searchPlaceholder: 'साहित्य किंवा ठिकाण शोधा...',
  noResourcesFound: 'कोणतेही साहित्य सापडले नाही.',
  types: {
    vehicle: 'वाहन / बोट',
    food: 'अन्नधान्य',
    water: 'पिण्याचे पाणी',
    medical: 'वैद्यकीय मदत',
    other: 'इतर साहित्य',
  },
  statuses: {
    available: 'उपलब्ध',
    inUse: 'वापरात',
    needed: 'आवश्यक',
  },
};

VERNACULAR_VOLUNTEER.gu = {
  ...VERNACULAR_VOLUNTEER.hi,
  pageTitle: 'સામુદાયિક સંસાધન કેન્દ્ર',
  pageSubtitle: 'સ્વયંસેવક સંકલન અને રાહત સામગ્રી વ્યવસ્થાપન',
  listResourceBtn: 'સંસાધન નોંધો',
  tabResources: 'ઉપલબ્ધ સંસાધનો',
  tabRescueML: 'બચાવ સંદેશ વિશ્લેષણ',
  formTitle: 'નવી નોંધણી',
  btnCancel: 'રદ કરો',
  btnPost: 'નોંધો',
  filterAll: 'બધું',
  searchPlaceholder: 'સંસાધનો અથવા સ્થળ શોધો...',
  noResourcesFound: 'કોઈ સંસાધન મળ્યું નથી.',
  types: {
    vehicle: 'વાહન / હોડી',
    food: 'અનાજ અને ખોરાક',
    water: 'પીવાનું પાણી',
    medical: 'તબીબી સહાય',
    other: 'અન્ય સામગ્રી',
  },
  statuses: {
    available: 'ઉપલબ્ધ',
    inUse: 'ઉપયોગમાં',
    needed: 'જરૂર છે',
  },
};

VERNACULAR_VOLUNTEER.bn = {
  ...VERNACULAR_VOLUNTEER.hi,
  pageTitle: 'কমিউনিটি ত্রাণ সম্পদ কেন্দ্র',
  pageSubtitle: 'স্বেচ্ছাসেবক সমন্বয় ও ত্রাণ সামগ্রী বিতরণ',
  listResourceBtn: 'ত্রাণ সামগ্রী যুক্ত করুন',
  tabResources: 'উপলব্ধ সামগ্রী',
  tabRescueML: 'উদ্ধার বার্তা বিশ্লেষণ',
  formTitle: 'নতুন সামগ্রীর তালিকাভুক্তকরণ',
  btnCancel: 'বাতিল',
  btnPost: 'যুক্ত করুন',
  filterAll: 'সব',
  searchPlaceholder: 'সামগ্রী বা এলাকা অনুসন্ধান করুন...',
  noResourcesFound: 'কোনো ত্রাণ সামগ্রী পাওয়া যায়নি।',
  types: {
    vehicle: 'যানবাহন / নৌকা',
    food: 'খাদ্য সামগ্রী',
    water: 'বিশুদ্ধ পানীয় জল',
    medical: 'চিকিৎসা সহায়তা',
    other: 'অন্যান্য ত্রাণ',
  },
  statuses: {
    available: 'উপলব্ধ',
    inUse: 'ব্যবহৃত হচ্ছে',
    needed: 'প্রয়োজন',
  },
};

VERNACULAR_VOLUNTEER.as = {
  ...VERNACULAR_VOLUNTEER.bn,
  pageTitle: 'সামূহিক সাহায্য সম্পদ কেন্দ্ৰ',
  pageSubtitle: 'স্বেচ্ছাসেৱক সমন্বয় আৰু সাহায্য সামগ্ৰী পৰিচালনা',
  listResourceBtn: 'সাহায্য সামগ্ৰী যোগ কৰক',
  tabResources: 'উপলব্ধ সামগ্ৰী',
  tabRescueML: 'উদ্ধাৰ বাৰ্তা বিশ্লেষণ',
  formTitle: 'নতুন সামগ্ৰীৰ তালিকা',
  btnCancel: 'বাতিল কৰক',
  btnPost: 'যোগ কৰক',
  filterAll: 'সকলো',
  searchPlaceholder: 'সামগ্ৰী বা স্থান সন্ধান কৰক...',
  noResourcesFound: 'কোনো সামগ্ৰী পোৱা নগ’ল।',
};

// Disasters Dictionary
export interface DisastersDictionary {
  regionalTelemetry: string;
  nationalFeed: string;
  neuralPredictions: string;
  noActiveDisasters: string;
  noActiveDesc: string;
  noRegionalActivity: string;
  scanningTelemetry: string;
  localizedBadge: string;
  totalBadge: string;
  docsBtn: string;
  telemetryMapBtn: string;
  magnitude: string;
  coordinates: string;
  eventId: string;
  probBadge: string;
  mlInferenceBadge: string;
  expectedIn: string;
  kmUnit: string;
  unknownTime: string;
  officialSource: string;
  reportSource: string;
  dayUnit: string;
  types: Record<string, string>;
  severities: Record<string, string>;
}

export const VERNACULAR_DISASTERS: Record<SupportedLanguageCode, DisastersDictionary> = {
  ml: {
    regionalTelemetry: 'മേഖലാ നിരീക്ഷണം (1000 കി.മീ പരിധി)',
    nationalFeed: 'ദേശീയ ഔദ്യോഗിക ദുരന്ത വിവരങ്ങൾ',
    neuralPredictions: 'ന്യൂറൽ നെറ്റ്‌വർക്ക് അപകടസാധ്യതാ പ്രവചനം',
    noActiveDisasters: 'സജീവ ദുരന്തങ്ങളൊന്നും റിപ്പോർട്ട് ചെയ്തിട്ടില്ല',
    noActiveDesc: 'നിലവിൽ ഭീഷണികളില്ല. നിരീക്ഷണ സംവിധാനങ്ങൾ സജീവമാണ്.',
    noRegionalActivity: 'ഈ മേഖലയിൽ അപായ സൂചനകളില്ല',
    scanningTelemetry: 'ഔദ്യോഗിക സ്ഥിരീകരണത്തിനായി വിവരങ്ങൾ പരിശോധിക്കുന്നു...',
    localizedBadge: 'മേഖലയിൽ ഉള്ളവ',
    totalBadge: 'ആകെ റിപ്പോർട്ടുകൾ',
    docsBtn: 'വിവരങ്ങൾ',
    telemetryMapBtn: 'ഭൂപടത്തിൽ കാണുക',
    magnitude: 'തീവ്രത:',
    coordinates: 'ഭൂമിശാസ്ത്ര നിർദ്ദേശാങ്കങ്ങൾ:',
    eventId: 'ഇവന്റ് ഐഡി:',
    probBadge: 'സാധ്യത',
    mlInferenceBadge: 'എഐ നിഗമനം',
    expectedIn: 'പ്രതീക്ഷിക്കുന്നത്',
    kmUnit: 'കി.മീ',
    unknownTime: 'ലഭ്യമല്ല',
    officialSource: 'ഔദ്യോഗികം',
    reportSource: 'റിപ്പോർട്ട്',
    dayUnit: 'ദിവസം',
    types: {
      flood: 'വെള്ളപ്പൊക്കം',
      earthquake: 'ഭൂകമ്പം',
      cyclone: 'ചുഴലിക്കാറ്റ്',
      wildfire: 'കാട്ടുതീ',
      fire: 'തീപിടുത്തം',
      landslide: 'ഉരുൾപൊട്ടൽ',
      drought: 'വരൾച്ച',
      tsunami: 'സുനാമി',
      cloudburst: 'മേഘവിസ്ഫോടനം',
    },
    severities: {
      critical: 'അതിതീവ്രം',
      high: 'തീവ്രം',
      moderate: 'മിതമായത്',
      low: 'കുറഞ്ഞത്',
    },
  },
  hi: {
    regionalTelemetry: 'क्षेत्रीय टेलीमेट्री (1000 किमी)',
    nationalFeed: 'राष्ट्रीय सत्यापित आपदाएं',
    neuralPredictions: 'न्यूरल जोखिम भविष्यवाणी',
    noActiveDisasters: 'कोई सक्रिय आपदा नहीं',
    noActiveDesc: 'वर्तमान में कोई सक्रिय आपदा रिपोर्ट नहीं है।',
    noRegionalActivity: 'कोई क्षेत्रीय गतिविधि नहीं',
    scanningTelemetry: 'सत्यापन के लिए टेलीमेट्री स्कैन की जा रही है...',
    localizedBadge: 'स्थानीय',
    totalBadge: 'कुल',
    docsBtn: 'दस्तावेज़',
    telemetryMapBtn: 'टेलीमेट्री मानचित्र',
    magnitude: 'तीव्रता:',
    coordinates: 'निर्देशांक:',
    eventId: 'घटना आईडी:',
    probBadge: 'संभावना',
    mlInferenceBadge: 'एआई अनुमान',
    expectedIn: 'अपेक्षित',
    kmUnit: 'किमी',
    unknownTime: 'अनुपलब्ध',
    officialSource: 'आधिकारिक',
    reportSource: 'रिपोर्ट',
    dayUnit: 'दिन',
    types: {
      flood: 'बाढ़',
      earthquake: 'भूकंप',
      cyclone: 'चक्रवात',
      wildfire: 'जंगल की आग',
      fire: 'आग',
      landslide: 'भूस्खलन',
      drought: 'सूखा',
      tsunami: 'सुनामी',
      cloudburst: 'बादल फटना',
    },
    severities: {
      critical: 'अति गंभीर',
      high: 'गंभीर',
      moderate: 'मध्यम',
      low: 'कम',
    },
  },
  en: {
    regionalTelemetry: 'REGIONAL TELEMETRY (1000 KM)',
    nationalFeed: 'NATIONAL VERIFIED FEED',
    neuralPredictions: 'NEURAL RISK PREDICTIONS',
    noActiveDisasters: 'No Active Disasters',
    noActiveDesc: 'No verified disasters with official reports found.',
    noRegionalActivity: 'No Regional Activity',
    scanningTelemetry: 'Scanning telemetry for official verification...',
    localizedBadge: 'LOCALIZED',
    totalBadge: 'TOTAL',
    docsBtn: 'DOCS',
    telemetryMapBtn: 'TELEMETRY MAP',
    magnitude: 'Magnitude:',
    coordinates: 'Coordinates:',
    eventId: 'Event ID:',
    probBadge: 'PROB',
    mlInferenceBadge: 'ML INFERENCE',
    expectedIn: 'Expected in',
    kmUnit: 'KM',
    unknownTime: 'Unknown',
    officialSource: 'Official',
    reportSource: 'Report',
    dayUnit: 'd',
    types: {
      flood: 'Flood',
      earthquake: 'Earthquake',
      cyclone: 'Cyclone',
      wildfire: 'Wildfire',
      fire: 'Fire',
      landslide: 'Landslide',
      drought: 'Drought',
      tsunami: 'Tsunami',
      cloudburst: 'Cloudburst',
    },
    severities: {
      critical: 'Critical',
      high: 'High',
      moderate: 'Moderate',
      low: 'Low',
    },
  },
  ta: {
    regionalTelemetry: 'பிராந்திய அளவீடுகள் (1000 கி.மீ)',
    nationalFeed: 'தேசிய சரிபார்க்கப்பட்ட பேரிடர்கள்',
    neuralPredictions: 'AI ஆபத்து கணிப்புகள்',
    noActiveDisasters: 'செயலில் உள்ள பேரிடர்கள் இல்லை',
    noActiveDesc: 'தற்போது எந்தவொரு செயலில் உள்ள பேரிடரும் இல்லை.',
    noRegionalActivity: 'பிராந்தியத்தில் எந்த ஆபத்தும் இல்லை',
    scanningTelemetry: 'சரிபார்ப்பிற்காக தரவுகள் ஆராயப்படுகின்றன...',
    localizedBadge: 'உள்ளூர்',
    totalBadge: 'மொத்தம்',
    docsBtn: 'ஆவணங்கள்',
    telemetryMapBtn: 'வரைபடம்',
    magnitude: 'தீவிரம்:',
    coordinates: 'ஆயத்தொலைவுகள்:',
    eventId: 'நிகழ்வு எண்:',
    probBadge: 'வாய்ப்பு',
    mlInferenceBadge: 'AI கணிப்பு',
    expectedIn: 'எதிர்பார்க்கப்படுகிறது',
    kmUnit: 'கி.மீ',
    unknownTime: 'தெரியவில்லை',
    officialSource: 'அதிகாரப்பூர்வ',
    reportSource: 'அறிக்கை',
    dayUnit: 'நாட்கள்',
    types: {
      flood: 'வெள்ளம்',
      earthquake: 'நிலநடுக்கம்',
      cyclone: 'புயல்',
      wildfire: 'காட்டுத்தீ',
      fire: 'தீ விபத்து',
      landslide: 'நிலச்சரிவு',
      drought: 'வறட்சி',
      tsunami: 'சுனாமி',
      cloudburst: 'மேகவெடிப்பு',
    },
    severities: {
      critical: 'மிகவும் தீவிரமானது',
      high: 'அதிதீவிரம்',
      moderate: 'மிதமானது',
      low: 'குறைவு',
    },
  },
  te: {
    regionalTelemetry: 'ప్రాంతీయ సమాచారం (1000 కి.மீ)',
    nationalFeed: 'జాతీయ ధృవీకరించబడిన విపత్తులు',
    neuralPredictions: 'AI ప్రమాద అంచనాలు',
    noActiveDisasters: 'క్రియాశీల విపత్తులు లేవు',
    noActiveDesc: 'ప్రస్తుతం క్రియాశీల విపత్తు నివేదికలు లేవు.',
    noRegionalActivity: 'ప్రాంతీయ కార్యాచరణ లేదు',
    scanningTelemetry: 'ధృవీకరణ కోసం టెలిమెట్రీ పరిశీలిస్తోంది...',
    localizedBadge: 'స్థానికం',
    totalBadge: 'మొత్తం',
    docsBtn: 'పత్రాలు',
    telemetryMapBtn: 'మ్యాప్',
    magnitude: 'తీవ్రత:',
    coordinates: 'కోఆర్డినేట్లు:',
    eventId: 'ఈవెంట్ ఐడీ:',
    probBadge: 'సంభావ్యత',
    mlInferenceBadge: 'AI అంచనా',
    expectedIn: 'అంచనా వేయబడింది',
    kmUnit: 'కి.మీ',
    unknownTime: 'అందుబాటులో లేదు',
    officialSource: 'అధికారిక',
    reportSource: 'నివేదిక',
    dayUnit: 'రోజులు',
    types: {
      flood: 'వరద',
      earthquake: 'భూకంపం',
      cyclone: 'తుఫాను',
      wildfire: 'కార్చిచ్చు',
      fire: 'అగ్నిప్రమాదం',
      landslide: 'కొండచరియలు విరిగిపడటం',
      drought: 'కరువు',
      tsunami: 'సునామి',
      cloudburst: 'క్లౌడ్‌బర్స్ట్',
    },
    severities: {
      critical: 'అత్యంత ప్రమాదకరం',
      high: 'తీవ్రమైనది',
      moderate: 'మధ్యస్థం',
      low: 'తక్కువ',
    },
  },
  mr: {
    regionalTelemetry: 'प्रादेशिक निरीक्षण (१००० किमी)',
    nationalFeed: 'राष्ट्रीय प्रमाणित आपत्ती',
    neuralPredictions: 'AI संभाव्य धोका अंदाज',
    noActiveDisasters: 'सक्रिय आपत्ती नाही',
    noActiveDesc: 'सध्या कोणतीही सक्रिय आपत्ती अहवाल नाही.',
    noRegionalActivity: 'कोणतीही प्रादेशिक हालचाल नाही',
    scanningTelemetry: 'प्रमाणीकरणासाठी डेटा तपासला जात आहे...',
    localizedBadge: 'स्थानिक',
    totalBadge: 'एकूण',
    docsBtn: 'माहिती',
    telemetryMapBtn: 'नकाशा',
    magnitude: 'तीव्रता:',
    coordinates: 'अक्षांश-रेखांश:',
    eventId: 'इव्हेंट आयडी:',
    probBadge: 'संभाव्यता',
    mlInferenceBadge: 'AI निष्कर्ष',
    expectedIn: 'अपेक्षित',
    kmUnit: 'किमी',
    unknownTime: 'अनुपलब्ध',
    officialSource: 'अधिकृत',
    reportSource: 'अहवाल',
    dayUnit: 'दिवस',
    types: {
      flood: 'पूर',
      earthquake: 'भूकंप',
      cyclone: 'चक्रीवादळ',
      wildfire: 'वणवा',
      fire: 'आग',
      landslide: 'दरड कोसळणे',
      drought: 'दुष्काळ',
      tsunami: 'सुनामी',
      cloudburst: 'ढगफुटी',
    },
    severities: {
      critical: 'अति तीव्र',
      high: 'तीव्र',
      moderate: 'मध्यम',
      low: 'कमी',
    },
  },
  gu: {
    regionalTelemetry: 'પ્રાદેશિક અવલોકન (1000 કિમી)',
    nationalFeed: 'રાષ્ટ્રીય ચકાસાયેલ આપત્તિઓ',
    neuralPredictions: 'AI જોખમ આગાહી',
    noActiveDisasters: 'કોઈ સક્રિય આપત્તિ નથી',
    noActiveDesc: 'હાલમાં કોઈ સક્રિય આપત્તિ અહેવાલ નથી.',
    noRegionalActivity: 'કોઈ પ્રાદેશિક ગતિવિધિ નથી',
    scanningTelemetry: 'ચકાસણી માટે ટેલિમેટ્રી સ્કેન થઈ રહી છે...',
    localizedBadge: 'સ્થાનિક',
    totalBadge: 'કુલ',
    docsBtn: 'દસ્તાવેજ',
    telemetryMapBtn: 'નકશો',
    magnitude: 'તીવ્રતા:',
    coordinates: 'અક્ષાંશ-રેખાંશ:',
    eventId: 'ઇવેન્ટ આઈડી:',
    probBadge: 'સંભાવના',
    mlInferenceBadge: 'AI અનુમાન',
    expectedIn: 'અપેક્ષિત',
    kmUnit: 'કિમી',
    unknownTime: 'અનુપલબ્ધ',
    officialSource: 'સત્તાવાર',
    reportSource: 'અહેવાલ',
    dayUnit: 'દિવસ',
    types: {
      flood: 'પૂર',
      earthquake: 'ભૂકંપ',
      cyclone: 'વાવાઝોડું',
      wildfire: 'દાવાનળ',
      fire: 'આગ',
      landslide: 'ભૂસ્ખલન',
      drought: 'દુષ્કાળ',
      tsunami: 'સુનામી',
      cloudburst: 'વાદળ ફાટવું',
    },
    severities: {
      critical: 'અતિ ગંભીર',
      high: 'ગંભીર',
      moderate: 'મધ્યમ',
      low: 'ઓછું',
    },
  },
  bn: {
    regionalTelemetry: 'আঞ্চলিক পর্যবেক্ষণ (১০০০ কিমি)',
    nationalFeed: 'জাতীয় যাচাইকৃত দুর্যোগ তালিকা',
    neuralPredictions: 'AI ঝুঁকি পূর্বাভাস',
    noActiveDisasters: 'কোনো সক্রিয় দুর্যোগ নেই',
    noActiveDesc: 'বর্তমানে কোনো সক্রিয় দুর্যোগ রিপোর্ট নেই।',
    noRegionalActivity: 'কোনো আঞ্চলিক সতর্কতা নেই',
    scanningTelemetry: 'যাচাইকরণের জন্য তথ্য স্ক্যান করা হচ্ছে...',
    localizedBadge: 'স্থানীয়',
    totalBadge: 'মোট',
    docsBtn: 'নথিপত্র',
    telemetryMapBtn: 'মানচিত্র',
    magnitude: 'মাত্রা:',
    coordinates: 'স্থানাঙ্ক:',
    eventId: 'ইভেন্ট আইডি:',
    probBadge: 'সম্ভাবনা',
    mlInferenceBadge: 'AI অনুমান',
    expectedIn: 'প্রত্যাশিত',
    kmUnit: 'কিমি',
    unknownTime: 'অনুপলব্ধ',
    officialSource: 'সরকারি',
    reportSource: 'প্রতিবেদন',
    dayUnit: 'দিন',
    types: {
      flood: 'বন্যা',
      earthquake: 'ভূমিকম্প',
      cyclone: 'ঘূর্ণিঝড়',
      wildfire: 'দাবানল',
      fire: 'অগ্নিকাণ্ড',
      landslide: 'ভূমিধস',
      drought: 'খরা',
      tsunami: 'সুনামি',
      cloudburst: 'মেঘভাঙা বৃষ্টি',
    },
    severities: {
      critical: 'অত্যন্ত সংকটজনক',
      high: 'উচ্চ',
      moderate: 'মাঝারি',
      low: 'কম',
    },
  },
  as: {
    regionalTelemetry: 'আঞ্চলিক নিৰীক্ষণ (১০০০ কিমি)',
    nationalFeed: 'জাতীয় নিৰীক্ষিত দুৰ্যোগ',
    neuralPredictions: 'AI বিপদৰ আগজাননী',
    noActiveDisasters: 'কোনো সক্ৰিয় দুৰ্যোগ নাই',
    noActiveDesc: 'বৰ্তমান কোনো সক্ৰিয় দুৰ্যোগ নাই।',
    noRegionalActivity: 'কোনো আঞ্চলিক বিপদ নাই',
    scanningTelemetry: 'সত্যতা নিৰ্ধাৰণৰ বাবে স্কেন কৰা হৈছে...',
    localizedBadge: 'স্থানীয়',
    totalBadge: 'মুঠ',
    docsBtn: 'তথ্য',
    telemetryMapBtn: 'মানচিত্ৰ',
    magnitude: 'প্ৰাবল্য:',
    coordinates: 'স্থানাংক:',
    eventId: 'ঘটনা আইডি:',
    probBadge: 'সম্ভাৱনা',
    mlInferenceBadge: 'AI অনুমান',
    expectedIn: 'প্ৰত্যাশিত',
    kmUnit: 'কিমি',
    unknownTime: 'অনুপলব্ধ',
    officialSource: 'চৰকাৰী',
    reportSource: 'প্ৰতিবেদন',
    dayUnit: 'দিন',
    types: {
      flood: 'বানপানী',
      earthquake: 'ভূমিকম্প',
      cyclone: 'ঘূর্ণিবতাহ',
      wildfire: 'বনজুই',
      fire: 'অগ্নিসংযোগ',
      landslide: 'ভূমিস্খলন',
      drought: 'খৰাং',
      tsunami: 'ছুনামি',
      cloudburst: 'মেঘভঙা বৰষুণ',
    },
    severities: {
      critical: 'চৰম সংকটজনক',
      high: 'উচ্চ',
      moderate: 'মধ্যমীয়া',
      low: 'কম',
    },
  },
};
