import re

new_disasters_code = """// Disasters Dictionary
export interface DisastersDictionary {
  regionalTelemetry: string;
  nationalFeed: string;
  neuralPredictions: string;
  noActiveDisasters: string;
  noActiveDesc: string;
  noRegionalActivity: string;
  scanningTelemetry: string;
  localizedBadge: string;
  totalBadge: string;
  docsBtn: string;
  telemetryMapBtn: string;
  magnitude: string;
  coordinates: string;
  eventId: string;
  probBadge: string;
  mlInferenceBadge: string;
  expectedIn: string;
  kmUnit: string;
  unknownTime: string;
  officialSource: string;
  reportSource: string;
  dayUnit: string;
  types: Record<string, string>;
  severities: Record<string, string>;
}

export const VERNACULAR_DISASTERS: Record<SupportedLanguageCode, DisastersDictionary> = {
  ml: {
    regionalTelemetry: 'മേഖലാ നിരീക്ഷണം (1000 കി.മീ പരിധി)',
    nationalFeed: 'ദേശീയ ഔദ്യോഗിക ദുരന്ത വിവരങ്ങൾ',
    neuralPredictions: 'ന്യൂറൽ നെറ്റ്‌വർക്ക് അപകടസാധ്യതാ പ്രവചനം',
    noActiveDisasters: 'സജീവ ദുരന്തങ്ങളൊന്നും റിപ്പോർട്ട് ചെയ്തിട്ടില്ല',
    noActiveDesc: 'നിലവിൽ ഭീഷണികളില്ല. നിരീക്ഷണ സംവിധാനങ്ങൾ സജീവമാണ്.',
    noRegionalActivity: 'ഈ മേഖലയിൽ അപായ സൂചനകളില്ല',
    scanningTelemetry: 'ഔദ്യോഗിക സ്ഥിരീകരണത്തിനായി വിവരങ്ങൾ പരിശോധിക്കുന്നു...',
    localizedBadge: 'മേഖലയിൽ ഉള്ളവ',
    totalBadge: 'ആകെ റിപ്പോർട്ടുകൾ',
    docsBtn: 'വിവരങ്ങൾ',
    telemetryMapBtn: 'ഭൂപടത്തിൽ കാണുക',
    magnitude: 'തീവ്രത:',
    coordinates: 'ഭൂമിശാസ്ത്ര നിർദ്ദേശാങ്കങ്ങൾ:',
    eventId: 'ഇവന്റ് ഐഡി:',
    probBadge: 'സാധ്യത',
    mlInferenceBadge: 'എഐ നിഗമനം',
    expectedIn: 'പ്രതീക്ഷിക്കുന്നത്',
    kmUnit: 'കി.മീ',
    unknownTime: 'ലഭ്യമല്ല',
    officialSource: 'ഔദ്യോഗികം',
    reportSource: 'റിപ്പോർട്ട്',
    dayUnit: 'ദിവസം',
    types: {
      flood: 'വെള്ളപ്പൊക്കം',
      earthquake: 'ഭൂകമ്പം',
      cyclone: 'ചുഴലിക്കാറ്റ്',
      wildfire: 'കാട്ടുതീ',
      fire: 'തീപിടുത്തം',
      landslide: 'ഉരുൾപൊട്ടൽ',
      drought: 'വരൾച്ച',
      tsunami: 'സുനാമി',
      cloudburst: 'മേഘവിസ്ഫോടനം',
    },
    severities: {
      critical: 'അതിതീവ്രം',
      high: 'തീവ്രം',
      moderate: 'മിതമായത്',
      low: 'കുറഞ്ഞത്',
    },
  },
  hi: {
    regionalTelemetry: 'क्षेत्रीय टेलीमेट्री (1000 किमी)',
    nationalFeed: 'राष्ट्रीय सत्यापित आपदाएं',
    neuralPredictions: 'न्यूरल जोखिम भविष्यवाणी',
    noActiveDisasters: 'कोई सक्रिय आपदा नहीं',
    noActiveDesc: 'वर्तमान में कोई सक्रिय आपदा रिपोर्ट नहीं है।',
    noRegionalActivity: 'कोई क्षेत्रीय गतिविधि नहीं',
    scanningTelemetry: 'सत्यापन के लिए टेलीमेट्री स्कैन की जा रही है...',
    localizedBadge: 'स्थानीय',
    totalBadge: 'कुल',
    docsBtn: 'दस्तावेज़',
    telemetryMapBtn: 'टेलीमेट्री मानचित्र',
    magnitude: 'तीव्रता:',
    coordinates: 'निर्देशांक:',
    eventId: 'घटना आईडी:',
    probBadge: 'संभावना',
    mlInferenceBadge: 'एआई अनुमान',
    expectedIn: 'अपेक्षित',
    kmUnit: 'किमी',
    unknownTime: 'अनुपलब्ध',
    officialSource: 'आधिकारिक',
    reportSource: 'रिपोर्ट',
    dayUnit: 'दिन',
    types: {
      flood: 'बाढ़',
      earthquake: 'भूकंप',
      cyclone: 'चक्रवात',
      wildfire: 'जंगल की आग',
      fire: 'आग',
      landslide: 'भूस्खलन',
      drought: 'सूखा',
      tsunami: 'सुनामी',
      cloudburst: 'बादल फटना',
    },
    severities: {
      critical: 'अति गंभीर',
      high: 'गंभीर',
      moderate: 'मध्यम',
      low: 'कम',
    },
  },
  en: {
    regionalTelemetry: 'REGIONAL TELEMETRY (1000 KM)',
    nationalFeed: 'NATIONAL VERIFIED FEED',
    neuralPredictions: 'NEURAL RISK PREDICTIONS',
    noActiveDisasters: 'No Active Disasters',
    noActiveDesc: 'No verified disasters with official reports found.',
    noRegionalActivity: 'No Regional Activity',
    scanningTelemetry: 'Scanning telemetry for official verification...',
    localizedBadge: 'LOCALIZED',
    totalBadge: 'TOTAL',
    docsBtn: 'DOCS',
    telemetryMapBtn: 'TELEMETRY MAP',
    magnitude: 'Magnitude:',
    coordinates: 'Coordinates:',
    eventId: 'Event ID:',
    probBadge: 'PROB',
    mlInferenceBadge: 'ML INFERENCE',
    expectedIn: 'Expected in',
    kmUnit: 'KM',
    unknownTime: 'Unknown',
    officialSource: 'Official',
    reportSource: 'Report',
    dayUnit: 'd',
    types: {
      flood: 'Flood',
      earthquake: 'Earthquake',
      cyclone: 'Cyclone',
      wildfire: 'Wildfire',
      fire: 'Fire',
      landslide: 'Landslide',
      drought: 'Drought',
      tsunami: 'Tsunami',
      cloudburst: 'Cloudburst',
    },
    severities: {
      critical: 'Critical',
      high: 'High',
      moderate: 'Moderate',
      low: 'Low',
    },
  },
  ta: {
    regionalTelemetry: 'பிராந்திய அளவீடுகள் (1000 கி.மீ)',
    nationalFeed: 'தேசிய சரிபார்க்கப்பட்ட பேரிடர்கள்',
    neuralPredictions: 'AI ஆபத்து கணிப்புகள்',
    noActiveDisasters: 'செயலில் உள்ள பேரிடர்கள் இல்லை',
    noActiveDesc: 'தற்போது எந்தவொரு செயலில் உள்ள பேரிடரும் இல்லை.',
    noRegionalActivity: 'பிராந்தியத்தில் எந்த ஆபத்தும் இல்லை',
    scanningTelemetry: 'சரிபார்ப்பிற்காக தரவுகள் ஆராயப்படுகின்றன...',
    localizedBadge: 'உள்ளூர்',
    totalBadge: 'மொத்தம்',
    docsBtn: 'ஆவணங்கள்',
    telemetryMapBtn: 'வரைபடம்',
    magnitude: 'தீவிரம்:',
    coordinates: 'ஆயத்தொலைவுகள்:',
    eventId: 'நிகழ்வு எண்:',
    probBadge: 'வாய்ப்பு',
    mlInferenceBadge: 'AI கணிப்பு',
    expectedIn: 'எதிர்பார்க்கப்படுகிறது',
    kmUnit: 'கி.மீ',
    unknownTime: 'தெரியவில்லை',
    officialSource: 'அதிகாரப்பூர்வ',
    reportSource: 'அறிக்கை',
    dayUnit: 'நாட்கள்',
    types: {
      flood: 'வெள்ளம்',
      earthquake: 'நிலநடுக்கம்',
      cyclone: 'புயல்',
      wildfire: 'காட்டுத்தீ',
      fire: 'தீ விபத்து',
      landslide: 'நிலச்சரிவு',
      drought: 'வறட்சி',
      tsunami: 'சுனாமி',
      cloudburst: 'மேகவெடிப்பு',
    },
    severities: {
      critical: 'மிகவும் தீவிரமானது',
      high: 'அதிதீவிரம்',
      moderate: 'மிதமானது',
      low: 'குறைவு',
    },
  },
  te: {
    regionalTelemetry: 'ప్రాంతీయ సమాచారం (1000 కి.மீ)',
    nationalFeed: 'జాతీయ ధృవీకరించబడిన విపత్తులు',
    neuralPredictions: 'AI ప్రమాద అంచనాలు',
    noActiveDisasters: 'క్రియాశీల విపత్తులు లేవు',
    noActiveDesc: 'ప్రస్తుతం క్రియాశీల విపత్తు నివేదికలు లేవు.',
    noRegionalActivity: 'ప్రాంతీయ కార్యాచరణ లేదు',
    scanningTelemetry: 'ధృవీకరణ కోసం టెలిమెట్రీ పరిశీలిస్తోంది...',
    localizedBadge: 'స్థానికం',
    totalBadge: 'మొత్తం',
    docsBtn: 'పత్రాలు',
    telemetryMapBtn: 'మ్యాప్',
    magnitude: 'తీవ్రత:',
    coordinates: 'కోఆర్డినేట్లు:',
    eventId: 'ఈవెంట్ ఐడీ:',
    probBadge: 'సంభావ్యత',
    mlInferenceBadge: 'AI అంచనా',
    expectedIn: 'అంచనా వేయబడింది',
    kmUnit: 'కి.మీ',
    unknownTime: 'అందుబాటులో లేదు',
    officialSource: 'అధికారిక',
    reportSource: 'నివేదిక',
    dayUnit: 'రోజులు',
    types: {
      flood: 'వరద',
      earthquake: 'భూకంపం',
      cyclone: 'తుఫాను',
      wildfire: 'కార్చిచ్చు',
      fire: 'అగ్నిప్రమాదం',
      landslide: 'కొండచరియలు విరిగిపడటం',
      drought: 'కరువు',
      tsunami: 'సునామి',
      cloudburst: 'క్లౌడ్‌బర్స్ట్',
    },
    severities: {
      critical: 'అత్యంత ప్రమాదకరం',
      high: 'తీవ్రమైనది',
      moderate: 'మధ్యస్థం',
      low: 'తక్కువ',
    },
  },
  mr: {
    regionalTelemetry: 'प्रादेशिक निरीक्षण (१००० किमी)',
    nationalFeed: 'राष्ट्रीय प्रमाणित आपत्ती',
    neuralPredictions: 'AI संभाव्य धोका अंदाज',
    noActiveDisasters: 'सक्रिय आपत्ती नाही',
    noActiveDesc: 'सध्या कोणतीही सक्रिय आपत्ती अहवाल नाही.',
    noRegionalActivity: 'कोणतीही प्रादेशिक हालचाल नाही',
    scanningTelemetry: 'प्रमाणीकरणासाठी डेटा तपासला जात आहे...',
    localizedBadge: 'स्थानिक',
    totalBadge: 'एकूण',
    docsBtn: 'माहिती',
    telemetryMapBtn: 'नकाशा',
    magnitude: 'तीव्रता:',
    coordinates: 'अक्षांश-रेखांश:',
    eventId: 'इव्हेंट आयडी:',
    probBadge: 'संभाव्यता',
    mlInferenceBadge: 'AI निष्कर्ष',
    expectedIn: 'अपेक्षित',
    kmUnit: 'किमी',
    unknownTime: 'अनुपलब्ध',
    officialSource: 'अधिकृत',
    reportSource: 'अहवाल',
    dayUnit: 'दिवस',
    types: {
      flood: 'पूर',
      earthquake: 'भूकंप',
      cyclone: 'चक्रीवादळ',
      wildfire: 'वणवा',
      fire: 'आग',
      landslide: 'दरड कोसळणे',
      drought: 'दुष्काळ',
      tsunami: 'सुनामी',
      cloudburst: 'ढगफुटी',
    },
    severities: {
      critical: 'अति तीव्र',
      high: 'तीव्र',
      moderate: 'मध्यम',
      low: 'कमी',
    },
  },
  gu: {
    regionalTelemetry: 'પ્રાદેશિક અવલોકન (1000 કિમી)',
    nationalFeed: 'રાષ્ટ્રીય ચકાસાયેલ આપત્તિઓ',
    neuralPredictions: 'AI જોખમ આગાહી',
    noActiveDisasters: 'કોઈ સક્રિય આપત્તિ નથી',
    noActiveDesc: 'હાલમાં કોઈ સક્રિય આપત્તિ અહેવાલ નથી.',
    noRegionalActivity: 'કોઈ પ્રાદેશિક ગતિવિધિ નથી',
    scanningTelemetry: 'ચકાસણી માટે ટેલિમેટ્રી સ્કેન થઈ રહી છે...',
    localizedBadge: 'સ્થાનિક',
    totalBadge: 'કુલ',
    docsBtn: 'દસ્તાવેજ',
    telemetryMapBtn: 'નકશો',
    magnitude: 'તીવ્રતા:',
    coordinates: 'અક્ષાંશ-રેખાંશ:',
    eventId: 'ઇવેન્ટ આઈડી:',
    probBadge: 'સંભાવના',
    mlInferenceBadge: 'AI અનુમાન',
    expectedIn: 'અપેક્ષિત',
    kmUnit: 'કિમી',
    unknownTime: 'અનુપલબ્ધ',
    officialSource: 'સત્તાવાર',
    reportSource: 'અહેવાલ',
    dayUnit: 'દિવસ',
    types: {
      flood: 'પૂર',
      earthquake: 'ભૂકંપ',
      cyclone: 'વાવાઝોડું',
      wildfire: 'દાવાનળ',
      fire: 'આગ',
      landslide: 'ભૂસ્ખલન',
      drought: 'દુષ્કાળ',
      tsunami: 'સુનામી',
      cloudburst: 'વાદળ ફાટવું',
    },
    severities: {
      critical: 'અતિ ગંભીર',
      high: 'ગંભીર',
      moderate: 'મધ્યમ',
      low: 'ઓછું',
    },
  },
  bn: {
    regionalTelemetry: 'আঞ্চলিক পর্যবেক্ষণ (১০০০ কিমি)',
    nationalFeed: 'জাতীয় যাচাইকৃত দুর্যোগ তালিকা',
    neuralPredictions: 'AI ঝুঁকি পূর্বাভাস',
    noActiveDisasters: 'কোনো সক্রিয় দুর্যোগ নেই',
    noActiveDesc: 'বর্তমানে কোনো সক্রিয় দুর্যোগ রিপোর্ট নেই।',
    noRegionalActivity: 'কোনো আঞ্চলিক সতর্কতা নেই',
    scanningTelemetry: 'যাচাইকরণের জন্য তথ্য স্ক্যান করা হচ্ছে...',
    localizedBadge: 'স্থানীয়',
    totalBadge: 'মোট',
    docsBtn: 'নথিপত্র',
    telemetryMapBtn: 'মানচিত্র',
    magnitude: 'মাত্রা:',
    coordinates: 'স্থানাঙ্ক:',
    eventId: 'ইভেন্ট আইডি:',
    probBadge: 'সম্ভাবনা',
    mlInferenceBadge: 'AI অনুমান',
    expectedIn: 'প্রত্যাশিত',
    kmUnit: 'কিমি',
    unknownTime: 'অনুপলব্ধ',
    officialSource: 'সরকারি',
    reportSource: 'প্রতিবেদন',
    dayUnit: 'দিন',
    types: {
      flood: 'বন্যা',
      earthquake: 'ভূমিকম্প',
      cyclone: 'ঘূর্ণিঝড়',
      wildfire: 'দাবানল',
      fire: 'অগ্নিকাণ্ড',
      landslide: 'ভূমিধস',
      drought: 'খরা',
      tsunami: 'সুনামি',
      cloudburst: 'মেঘভাঙা বৃষ্টি',
    },
    severities: {
      critical: 'অত্যন্ত সংকটজনক',
      high: 'উচ্চ',
      moderate: 'মাঝারি',
      low: 'কম',
    },
  },
  as: {
    regionalTelemetry: 'আঞ্চলিক নিৰীক্ষণ (১০০০ কিমি)',
    nationalFeed: 'জাতীয় নিৰীক্ষিত দুৰ্যোগ',
    neuralPredictions: 'AI বিপদৰ আগজাননী',
    noActiveDisasters: 'কোনো সক্ৰিয় দুৰ্যোগ নাই',
    noActiveDesc: 'বৰ্তমান কোনো সক্ৰিয় দুৰ্যোগ নাই।',
    noRegionalActivity: 'কোনো আঞ্চলিক বিপদ নাই',
    scanningTelemetry: 'সত্যতা নিৰ্ধাৰণৰ বাবে স্কেন কৰা হৈছে...',
    localizedBadge: 'স্থানীয়',
    totalBadge: 'মুঠ',
    docsBtn: 'তথ্য',
    telemetryMapBtn: 'মানচিত্ৰ',
    magnitude: 'প্ৰাবল্য:',
    coordinates: 'স্থানাংক:',
    eventId: 'ঘটনা আইডি:',
    probBadge: 'সম্ভাৱনা',
    mlInferenceBadge: 'AI অনুমান',
    expectedIn: 'প্ৰত্যাশিত',
    kmUnit: 'কিমি',
    unknownTime: 'অনুপলব্ধ',
    officialSource: 'চৰকাৰী',
    reportSource: 'প্ৰতিবেদন',
    dayUnit: 'দিন',
    types: {
      flood: 'বানপানী',
      earthquake: 'ভূমিকম্প',
      cyclone: 'ঘূর্ণিবতাহ',
      wildfire: 'বনজুই',
      fire: 'অগ্নিসংযোগ',
      landslide: 'ভূমিস্খলন',
      drought: 'খৰাং',
      tsunami: 'ছুনামি',
      cloudburst: 'মেঘভঙা বৰষুণ',
    },
    severities: {
      critical: 'চৰম সংকটজনক',
      high: 'উচ্চ',
      moderate: 'মধ্যমীয়া',
      low: 'কম',
    },
  },
};
"""

with open('src/utils/vernacularData.ts', 'r', encoding='utf-8') as f:
    text = f.read()

idx = text.find('// Disasters Dictionary')
if idx != -1:
    new_text = text[:idx] + new_disasters_code
    with open('src/utils/vernacularData.ts', 'w', encoding='utf-8') as f:
        f.write(new_text)
    print("Disasters dictionary successfully updated!")
else:
    print("// Disasters Dictionary not found!")
